/**
 * 生物化学 题目集 — 120题
 * 难度分布: common(60) / rare(36) / epic(18) / legendary(6)
 */
(function(){
var M=window.MediCard||{};M.QuestionBank=M.QuestionBank||{};
var S="生物化学",SI="biochemistry";
function Q(o){return{id:o.id,subject:S,subjectId:SI,difficulty:o.d,questionType:o.t||"single",cardType:o.ct||"attack",cardName:o.cn,energyCost:o.ec||1,cardEffect:o.ce,question:o.q,options:o.op,correctAnswers:o.a,explanation:o.e,textbookReference:o.r,knowledgePoint:o.kp,tags:o.tg};}
M.QuestionBank[SI]=[
// ===== Common (60) =====
Q({id:"biochem-common-001",d:"common",t:"single",ct:"attack",cn:"糖酵解启动",ec:1,ce:"造成3点伤害",q:"糖酵解途径中催化不可逆反应的三个关键酶是？",op:["A. 己糖激酶、磷酸果糖激酶-1、丙酮酸激酶","B. 己糖激酶、醛缩酶、烯醇化酶","C. 磷酸果糖激酶-1、磷酸甘油酸激酶、丙酮酸激酶","D. 葡萄糖-6-磷酸酶、果糖-1,6-二磷酸酶、丙酮酸羧化酶"],a:["A"],e:"糖酵解三个不可逆反应分别由己糖激酶(HK)、磷酸果糖激酶-1(PFK-1)和丙酮酸激酶(PK)催化，是糖酵解调控的关键位点。",r:"《生物化学与分子生物学》第9版 P96",kp:"糖酵解关键酶",tg:["糖酵解","不可逆反应"]}),
Q({id:"biochem-common-002",d:"common",t:"single",ct:"attack",cn:"TCA循环供能",ec:2,ce:"造成4点伤害",q:"三羧酸循环(TCA cycle)发生在线粒体的哪个部位？",op:["A. 线粒体基质","B. 线粒体外膜","C. 线粒体膜间隙","D. 线粒体内膜"],a:["A"],e:"TCA循环的8种酶均位于线粒体基质，只有琥珀酸脱氢酶(复合体II)结合在线粒体内膜上。",r:"《生物化学与分子生物学》第9版 P120",kp:"TCA循环定位",tg:["TCA循环","线粒体"]}),
Q({id:"biochem-common-003",d:"common",t:"single",ct:"heal",cn:"葡萄糖供能",ec:1,ce:"恢复3点HP",q:"1分子葡萄糖经有氧氧化净生成多少分子ATP？",op:["A. 30-32","B. 2","C. 36-38","D. 12"],a:["A"],e:"葡萄糖有氧氧化净生成约30-32分子ATP，更新后的计算考虑了胞质NADH穿梭的差异(苹果酸-天冬氨酸穿梭产2.5ATP/NADH，磷酸甘油穿梭产1.5ATP/NADH)。",r:"《生物化学与分子生物学》第9版 P135",kp:"ATP产量",tg:["有氧氧化","ATP"]}),
Q({id:"biochem-common-004",d:"common",t:"single",ct:"defense",cn:"脂肪酸β氧化",ec:2,ce:"获得3点护盾",q:"脂肪酸β-氧化的主要场所是？",op:["A. 线粒体基质","B. 胞质","C. 内质网","D. 过氧化物酶体"],a:["A"],e:"长链脂肪酸经肉碱转运入线粒体基质进行β-氧化，生成乙酰CoA、NADH和FADH₂。极长链脂肪酸先在过氧化物酶体进行部分β-氧化。",r:"《生物化学与分子生物学》第9版 P155",kp:"脂肪酸β-氧化",tg:["脂肪酸","β-氧化"]}),
Q({id:"biochem-common-005",d:"common",t:"single",ct:"attack",cn:"尿素循环排毒",ec:2,ce:"造成4点伤害",q:"尿素合成的场所和关键酶是？",op:["A. 肝脏线粒体+胞质，氨基甲酰磷酸合成酶I(CPS-I)","B. 肾脏，精氨酸酶","C. 肌肉，谷氨酰胺合成酶","D. 肠道，尿素酶"],a:["A"],e:"尿素循环部分在线粒体(CPS-I、OTC)，部分在胞质(ASS、ASL、精氨酸酶)进行。CPS-I是限速酶，被N-乙酰谷氨酸别构激活。",r:"《生物化学与分子生物学》第9版 P210",kp:"尿素循环",tg:["尿素循环","氨基酸代谢"]}),

// More common questions (6-60 using compact format)
Q({id:"biochem-common-006",d:"common",t:"truefalse",ct:"heal",cn:"DNA修复",ec:1,ce:"恢复2点HP",q:"DNA复制是半保留复制。",op:["A. 正确","B. 错误"],a:["A"],e:"Meselson和Stahl(1958)用¹⁵N标记实验证明DNA复制是半保留的：子代DNA双链各含一条亲代链和一条新生链。",r:"《生物化学与分子生物学》第9版 P300",kp:"DNA半保留复制",tg:["DNA复制","半保留"]}),
Q({id:"biochem-common-007",d:"common",t:"single",ct:"attack",cn:"氧化磷酸化",ec:2,ce:"造成4点伤害",q:"氧化磷酸化的化学渗透假说中，质子梯度建立在？",op:["A. 线粒体内膜两侧","B. 线粒体外膜两侧","C. 细胞膜两侧","D. 内质网膜两侧"],a:["A"],e:"电子传递链(复合体I/III/IV)将质子从线粒体基质泵入膜间隙，在线粒体内膜两侧建立电化学质子梯度，驱动ATP合酶合成ATP。",r:"《生物化学与分子生物学》第9版 P130",kp:"化学渗透假说",tg:["氧化磷酸化","质子梯度"]}),
Q({id:"biochem-common-008",d:"common",t:"single",ct:"attack",cn:"转氨酶活性",ec:1,ce:"造成3点伤害",q:"ALT(GPT)催化氨基从丙氨酸转移到？",op:["A. α-酮戊二酸→谷氨酸","B. 草酰乙酸→天冬氨酸","C. 丙酮酸→丙氨酸","D. 谷氨酰胺→谷氨酸"],a:["A"],e:"ALT催化:丙氨酸+α-酮戊二酸⇌丙酮酸+谷氨酸。AST催化:天冬氨酸+α-酮戊二酸⇌草酰乙酸+谷氨酸。两种转氨酶的辅酶均为磷酸吡哆醛(PLP/VitB6)。",r:"《生物化学与分子生物学》第9版 P205",kp:"转氨酶",tg:["ALT","转氨作用"]}),
Q({id:"biochem-common-009",d:"common",t:"single",ct:"defense",cn:"酮体供能防御",ec:2,ce:"获得3点护盾",q:"酮体在哪个器官合成，在哪个器官利用？",op:["A. 肝脏合成，脑/心/骨骼肌利用","B. 脑合成，肝脏利用","C. 肌肉合成，脑利用","D. 脂肪组织合成，肝脏利用"],a:["A"],e:"酮体(乙酰乙酸、β-羟丁酸、丙酮)在肝线粒体中由HMG-CoA合成酶催化合成，但肝脏缺乏琥珀酰CoA:乙酰乙酸CoA转移酶(SCOT)不能利用酮体。脑、心等可利用酮体供能。",r:"《生物化学与分子生物学》第9版 P162",kp:"酮体代谢",tg:["酮体","肝脏"]}),
Q({id:"biochem-common-010",d:"common",t:"single",ct:"heal",cn:"糖异生供能",ec:2,ce:"恢复4点HP",q:"糖异生的主要器官是？",op:["A. 肝脏和肾脏","B. 肌肉和心脏","C. 脑和红细胞","D. 脂肪组织"],a:["A"],e:"肝脏是主要的糖异生器官(维持血糖)，肾脏在长期饥饿时可贡献约40%的糖异生。糖异生利用乳酸( Cori循环)、甘油、生糖氨基酸和丙酸作为底物。",r:"《生物化学与分子生物学》第9版 P142",kp:"糖异生",tg:["糖异生","肝脏"]}),

// Quick generation of rest of common questions (11-60)
Q({id:"biochem-common-011",d:"common",t:"single",ct:"attack",cn:"胆固醇合成",ec:2,ce:"造成4点伤害",q:"胆固醇合成的限速酶是？",op:["A. HMG-CoA还原酶","B. HMG-CoA合成酶","C. 鲨烯合酶","D. 甲羟戊酸激酶"],a:["A"],e:"HMG-CoA还原酶催化HMG-CoA→甲羟戊酸(MVA)，是胆固醇合成的限速步骤。他汀类药物(statins)竞争性抑制此酶。",r:"《生化与分子生物学》第9版 P180",kp:"胆固醇合成",tg:["胆固醇","他汀"]}),
Q({id:"biochem-common-012",d:"common",t:"single",ct:"attack",cn:"嘌呤核苷酸合成",ec:2,ce:"造成3点伤害",q:"嘌呤核苷酸从头合成的关键起始底物是？",op:["A. PRPP(磷酸核糖焦磷酸)","B. 谷氨酰胺","C. 甘氨酸","D. 天冬氨酸"],a:["A"],e:"嘌呤核苷酸从头合成起始于PRPP，由PRPP合成酶催化。PRPP也是嘧啶核苷酸和NAD⁺/NADP⁺合成的共同前体。",r:"《生物化学与分子生物学》第9版 P225",kp:"嘌呤合成",tg:["PRPP","核苷酸合成"]}),
Q({id:"biochem-common-013",d:"common",t:"single",ct:"defense",cn:"脂溶性维生素",ec:1,ce:"获得2点护盾",q:"下列哪种维生素是水溶性的？",op:["A. 维生素C","B. 维生素A","C. 维生素D","D. 维生素E"],a:["A"],e:"维生素C(抗坏血酸)是水溶性维生素。维生素A、D、E、K为脂溶性维生素。",r:"《生物化学与分子生物学》第9版 P250",kp:"维生素分类",tg:["维生素","水溶性"]}),
Q({id:"biochem-common-014",d:"common",t:"single",ct:"attack",cn:"糖原分解",ec:2,ce:"造成4点伤害",q:"糖原磷酸化酶催化糖原分解的产物是？",op:["A. 葡萄糖-1-磷酸","B. 葡萄糖-6-磷酸","C. 游离葡萄糖","D. UDP-葡萄糖"],a:["A"],e:"糖原磷酸化酶催化α-1,4-糖苷键磷酸解，生成葡萄糖-1-磷酸(G1P)，G1P经磷酸葡萄糖变位酶转化为G6P进入糖酵解。",r:"《生物化学与分子生物学》第9版 P148",kp:"糖原分解",tg:["糖原磷酸化酶","G1P"]}),
Q({id:"biochem-common-015",d:"common",t:"single",ct:"heal",cn:"维生素B12",ec:2,ce:"恢复3点HP",q:"维生素B12(钴胺素)缺乏导致哪种氨基酸代谢异常？",op:["A. 同型半胱氨酸→蛋氨酸 (甲硫氨酸合酶受阻)","B. 苯丙氨酸→酪氨酸","C. 色氨酸→5-羟色胺","D. 谷氨酸→GABA"],a:["A"],e:"维生素B12是甲硫氨酸合酶的辅因子，催化同型半胱氨酸甲基化生成蛋氨酸，同时需要5-甲基四氢叶酸提供甲基。B12缺乏导致同型半胱氨酸血症和甲基丙二酸血症。",r:"《生物化学与分子生物学》第9版 P218",kp:"一碳单位代谢",tg:["维生素B12","同型半胱氨酸"]}),

// 16-60 — generating more questions
Q({id:"biochem-common-016",d:"common",t:"single",ct:"attack",cn:"酶的竞争性抑制",ec:2,ce:"造成3点伤害",q:"竞争性抑制剂对酶动力学参数的影响是？",op:["A. Km增大, Vmax不变","B. Km不变, Vmax降低","C. Km减小, Vmax不变","D. Km和Vmax均降低"],a:["A"],e:"竞争性抑制剂与底物竞争酶的活性中心，可通过增加底物浓度克服。Km表观增大(亲和力降低)，但Vmax不变(足够底物时可达最大速度)。",r:"《生物化学与分子生物学》第9版 P65",kp:"酶抑制动力学",tg:["竞争性抑制","米氏方程"]}),
Q({id:"biochem-common-017",d:"common",t:"single",ct:"defense",cn:"HDL保护",ec:1,ce:"获得3点护盾",q:"高密度脂蛋白(HDL)的主要功能是？",op:["A. 逆向胆固醇转运(RCT)","B. 向组织运送甘油三酯","C. 向组织运送胆固醇","D. 促进脂肪储存"],a:["A"],e:"HDL将外周组织(包括动脉壁)多余的胆固醇逆向转运至肝脏代谢排泄，具有抗动脉粥样硬化作用。",r:"《生物化学与分子生物学》第9版 P185",kp:"脂蛋白功能",tg:["HDL","逆向胆固醇转运"]}),
Q({id:"biochem-common-018",d:"common",t:"truefalse",ct:"attack",cn:"端粒酶延长",ec:2,ce:"造成3点伤害",q:"原核生物的mRNA通常是多顺反子(polycistronic)的。",op:["A. 正确","B. 错误"],a:["A"],e:"原核生物mRNA常为多顺反子(一个mRNA编码多个蛋白质，形成操纵子)，而真核生物mRNA通常为单顺反子(一个mRNA编码一个蛋白质)。",r:"《生物化学与分子生物学》第9版 P340",kp:"原核与真核转录差异",tg:["多顺反子","操纵子"]}),
Q({id:"biochem-common-019",d:"common",t:"single",ct:"attack",cn:"胰高血糖素信号",ec:2,ce:"造成4点伤害",q:"胰高血糖素在肝细胞中的第二信使是？",op:["A. cAMP","B. Ca²⁺","C. IP3","D. cGMP"],a:["A"],e:"胰高血糖素结合GPCR→激活Gs蛋白→激活腺苷酸环化酶→cAMP升高→激活PKA→磷酸化糖原磷酸化酶激酶等→促进糖原分解和糖异生。",r:"《生物化学与分子生物学》第9版 P260",kp:"激素信号转导",tg:["胰高血糖素","cAMP"]}),
Q({id:"biochem-common-020",d:"common",t:"single",ct:"heal",cn:"抗氧化修复",ec:2,ce:"恢复4点HP",q:"谷胱甘肽(GSH)还原酶使用哪种辅酶？",op:["A. NADPH","B. NADH","C. FADH₂","D. ATP"],a:["A"],e:"谷胱甘肽还原酶利用NADPH将GSSG还原为GSH，NADPH主要来自磷酸戊糖途径(G6PD催化)。G6PD缺乏症患者红细胞不能产生足够NADPH→GSH耗竭→氧化损伤→溶血。",r:"《生物化学与分子生物学》第9版 P175",kp:"谷胱甘肽代谢",tg:["GSH","NADPH"]}),

// 21-60 questions (abbreviated format for volume)
Q({id:"biochem-common-021",d:"common",ct:"attack",cn:"DNA聚合酶比对",ec:2,ce:"造成4点伤害",q:"真核生物DNA聚合酶α的主要功能是？",op:["A. 引物酶活性+合成短RNA-DNA引物","B. 前导链的连续合成","C. 滞后链的冈崎片段延伸","D. 线粒体DNA复制"],a:["A"],e:"Pol α含引物酶亚基，合成约10nt RNA+20-30nt DNA引物。Pol δ合成滞后链，Pol ε合成前导链，Pol γ复制线粒体DNA。",r:"《生化》P310",kp:"真核DNA聚合酶",tg:["DNA聚合酶","复制"]}),
Q({id:"biochem-common-022",d:"common",ct:"defense",cn:"凝血级联防御",ec:2,ce:"获得4点护盾",q:"维生素K依赖性凝血因子包括哪些？",op:["A. 凝血因子II, VII, IX, X","B. 凝血因子I, V, VIII, XIII","C. 凝血因子III, XI, XII","D. 凝血因子IV, VI"],a:["A"],e:"维生素K依赖的γ-羧化酶在肝细胞中将II/VII/IX/X因子前体N端的Glu残基羧化为Gla，赋予钙离子结合能力。华法林抑制维生素K循环。",r:"《生化》P255",kp:"凝血因子",tg:["维生素K","凝血"]}),
Q({id:"biochem-common-023",d:"common",ct:"attack",cn:"电子传递抑制",ec:3,ce:"造成5点伤害",q:"氰化物(CN⁻)的毒性机制是抑制电子传递链的哪个复合体？",op:["A. 复合体IV (细胞色素c氧化酶)","B. 复合体I (NADH脱氢酶)","C. 复合体III (细胞色素bc1)","D. 复合体II (琥珀酸脱氢酶)"],a:["A"],e:"CN⁻与复合体IV中细胞色素a3的Fe³⁺紧密结合，阻断电子传递给O₂，导致整个电子传递链停止和ATP耗竭，是剧毒。治疗:亚硝酸盐诱导高铁血红蛋白竞争CN⁻，再用硫代硫酸盐排毒。",r:"《生化》P132",kp:"电子传递链抑制剂",tg:["氰化物","复合体IV"]}),
Q({id:"biochem-common-024",d:"common",ct:"heal",cn:"磷酸戊糖途径",ec:2,ce:"恢复3点HP",q:"磷酸戊糖途径的生理意义不包括？",op:["A. 产生大量ATP","B. 提供核糖-5-磷酸","C. 提供NADPH","D. 维持还原型谷胱甘肽"],a:["A"],e:"磷酸戊糖途径产生NADPH(用于还原合成和抗氧化)和核糖-5-磷酸(核苷酸合成前体)，但不直接产生ATP。反应发生在胞质中。",r:"《生化》P170",kp:"磷酸戊糖途径",tg:["PPP","NADPH"]}),
Q({id:"biochem-common-025",d:"common",t:"single",ct:"attack",cn:"别构调节酶",ec:2,ce:"造成3点伤害",q:"磷酸果糖激酶-1(PFK-1)最强的别构激活剂是？",op:["A. 果糖-2,6-二磷酸","B. ATP","C. 柠檬酸","D. 葡萄糖-6-磷酸"],a:["A"],e:"果糖-2,6-二磷酸(F-2,6-BP)是PFK-1最强的别构激活剂(降低其对ATP抑制的敏感性)，由PFK-2/FBPase-2双功能酶催化合成，受胰岛素/胰高血糖素调控。ATP和柠檬酸是PFK-1的抑制剂。",r:"《生化》P100",kp:"PFK-1调控",tg:["F-2,6-BP","PFK-1"]}),

// Generating remaining common questions 26-60
Q({id:"biochem-common-026",d:"common",ct:"defense",cn:"热休克蛋白保护",ec:1,ce:"获得2点护盾",q:"热休克反应中上调的分子伴侣主要是？",op:["A. Hsp70和Hsp90","B. 泛素","C. Caspase","D. 细胞色素c"],a:["A"],e:"Hsp70和Hsp90帮助热变性蛋白重新折叠或靶向降解，受HSF1(热休克转录因子)调控。这属于蛋白质稳态应激反应。",r:"《生化》P370",kp:"热休克反应",tg:["Hsp70","蛋白质折叠"]}),
Q({id:"biochem-common-027",d:"common",ct:"attack",cn:"脂肪酸合成",ec:2,ce:"造成3点伤害",q:"脂肪酸从头合成中，乙酰CoA羧化酶催化乙酰CoA生成？",op:["A. 丙二酸单酰CoA","B. 棕榈酸","C. 丙酰CoA","D. 乙酰乙酰CoA"],a:["A"],e:"乙酰CoA羧化酶(ACC)是脂肪酸合成的限速酶，催化乙酰CoA羧化为丙二酸单酰CoA(需要生物素和ATP)。丙二酸单酰CoA为脂肪酸合成提供二碳单位。",r:"《生化》P158",kp:"脂肪酸合成",tg:["乙酰CoA羧化酶","丙二酸单酰CoA"]}),
Q({id:"biochem-common-028",d:"common",t:"truefalse",ct:"heal",cn:"复制叉修复",ec:1,ce:"恢复2点HP",q:"DNA复制时前导链(leading strand)是连续合成的。",op:["A. 正确","B. 错误"],a:["A"],e:"前导链沿模板链3'→5'方向连续合成(新生链5'→3')。滞后链不连续合成，形成冈崎片段。",r:"《生化》P305",kp:"DNA复制机制",tg:["前导链","复制叉"]}),
Q({id:"biochem-common-029",d:"common",ct:"attack",cn:"胆汁酸合成",ec:2,ce:"造成3点伤害",q:"胆汁酸由什么物质在肝脏中合成？",op:["A. 胆固醇","B. 甘油三酯","C. 磷脂","D. 脂肪酸"],a:["A"],e:"胆汁酸是胆固醇在肝脏中的主要代谢产物(经典途径由CYP7A1起始)，也是胆固醇从体内排出的主要方式。胆汁酸也是肠道信号分子(FXR/TGR5)。",r:"《生化》P190",kp:"胆汁酸合成",tg:["胆汁酸","胆固醇"]}),
Q({id:"biochem-common-030",d:"common",ct:"attack",cn:"ATP合酶旋转",ec:3,ce:"造成5点伤害",q:"ATP合酶( F₁F₀-ATPase)中负责催化ATP合成的亚基是？",op:["A. F₁的β亚基","B. F₀的c亚基","C. F₁的γ亚基","D. F₀的a亚基"],a:["A"],e:"F₁的β亚基含催化位点。γ亚基旋转引起β亚基构象变化(开放→松弛→紧密)，驱动ADP+Pi→ATP。质子流经F₀驱动γ亚基旋转。Boyer因此获1997年诺贝尔奖。",r:"《生化》P128",kp:"ATP合酶机制",tg:["ATP合酶","旋转催化"]}),

// Questions 31-60 (more biochemistry)
Q({id:"biochem-common-031",d:"common",ct:"heal",cn:"S-腺苷蛋氨酸",ec:2,ce:"恢复3点HP",q:"体内甲基化反应的主要甲基供体是？",op:["A. S-腺苷蛋氨酸(SAM)","B. 四氢叶酸","C. 维生素B12","D. 胆碱"],a:["A"],e:"SAM(S-腺苷甲硫氨酸)是体内最重要的甲基供体，参与DNA/组蛋白甲基化、神经递质合成、磷脂合成等100多种甲基转移反应。",r:"《生化》P215",kp:"一碳代谢",tg:["SAM","甲基化"]}),
Q({id:"biochem-common-032",d:"common",ct:"defense",cn:"胆红素代谢防御",ec:2,ce:"获得3点护盾",q:"血红素分解代谢的终产物是？",op:["A. 胆红素","B. 胆固醇","C. 尿酸","D. 肌酐"],a:["A"],e:"血红素经血红素加氧酶(HO-1)→胆绿素→胆绿素还原酶→胆红素(非结合/间接胆红素)，在肝脏与葡糖醛酸结合后经胆汁排出。",r:"《生化》P220",kp:"血红素代谢",tg:["胆红素","血红素"]}),
Q({id:"biochem-common-033",d:"common",ct:"attack",cn:"同型半胱氨酸毒性",ec:3,ce:"造成5点伤害",q:"高同型半胱氨酸血症是哪种疾病的独立危险因素？",op:["A. 动脉粥样硬化和血栓形成","B. 糖尿病","C. 感染性疾病","D. 自身免疫病"],a:["A"],e:"高同型半胱氨酸(>15μM)通过氧化应激、内质网应激和促进血栓形成等机制损伤血管内皮，是心血管疾病的独立危险因素。与叶酸/B12/B6缺乏相关。",r:"《生化》P219",kp:"同型半胱氨酸",tg:["同型半胱氨酸","心血管"]}),
Q({id:"biochem-common-034",d:"common",t:"single",ct:"attack",cn:"糖原合成",ec:2,ce:"造成3点伤害",q:"糖原合成酶的活性形式是？",op:["A. 去磷酸化形式(GS-a)","B. 磷酸化形式(GS-b)","C. 乙酰化形式","D. 泛素化形式"],a:["A"],e:"糖原合成酶被磷酸化后失活(GS-b)，去磷酸化后活化(GS-a)。胰岛素通过PP1去磷酸化激活糖原合成酶，胰高血糖素通过PKA磷酸化使其失活。这与糖原磷酸化酶的调控相反(磷酸化活化)。",r:"《生化》P150",kp:"糖原合成调控",tg:["糖原合成酶","磷酸化"]}),
Q({id:"biochem-common-035",d:"common",ct:"heal",cn:"硒代半胱氨酸",ec:2,ce:"恢复3点HP",q:"谷胱甘肽过氧化物酶的活性中心含哪种特殊氨基酸？",op:["A. 硒代半胱氨酸(Sec)","B. 羟脯氨酸","C. 羧基谷氨酸","D. 磷酸丝氨酸"],a:["A"],e:"谷胱甘肽过氧化物酶(GPX)的活性中心含硒代半胱氨酸(Sec)，由终止密码子UGA编码，是第21种蛋白质氨基酸。硒元素是必需微量元素。",r:"《生化》P252",kp:"硒代半胱氨酸",tg:["GPX","硒"]}),
Q({id:"biochem-common-036",d:"common",ct:"attack",cn:"底物水平磷酸化",ec:2,ce:"造成4点伤害",q:"TCA循环中唯一的底物水平磷酸化发生在哪一步？",op:["A. 琥珀酰CoA→琥珀酸","B. 异柠檬酸→α-酮戊二酸","C. α-酮戊二酸→琥珀酰CoA","D. 苹果酸→草酰乙酸"],a:["A"],e:"琥珀酰CoA合成酶催化琥珀酰CoA→琥珀酸，同时GDP+Pi→GTP(动物)或ADP+Pi→ATP(植物)，是TCA循环中唯一的底物水平磷酸化。",r:"《生化》P124",kp:"底物水平磷酸化",tg:["琥珀酰CoA","GTP"]}),
Q({id:"biochem-common-037",d:"common",ct:"defense",cn:"载脂蛋白关卡",ec:2,ce:"获得3点护盾",q:"LDL受体的配体结合结构域识别哪种载脂蛋白？",op:["A. ApoB-100和ApoE","B. ApoA-I","C. ApoC-II","D. ApoD"],a:["A"],e:"LDL受体识别LDL颗粒上的ApoB-100和ApoE，介导LDL的受体介导内吞。家族性高胆固醇血症(FH)常由LDL受体基因突变引起。",r:"《生化》P185",kp:"LDL受体",tg:["LDL受体","ApoB-100"]}),
Q({id:"biochem-common-038",d:"common",t:"truefalse",ct:"attack",cn:"RNA编辑修复",ec:2,ce:"造成3点伤害",q:"真核生物mRNA 5'端帽结构是7-甲基鸟苷( m⁷GpppN)。",op:["A. 正确","B. 错误"],a:["A"],e:"5'帽(m⁷GpppN)通过5'-5'三磷酸桥连接在mRNA 5'端，保护mRNA免于5'→3'外切酶降解，并促进翻译起始。",r:"《生化》P350",kp:"mRNA加工",tg:["5'帽","mRNA加工"]}),
Q({id:"biochem-common-039",d:"common",ct:"attack",cn:"嘌呤分解",ec:2,ce:"造成4点伤害",q:"人类嘌呤核苷酸分解代谢的终产物是？",op:["A. 尿酸","B. 尿素","C. 尿囊素","D. 氨"],a:["A"],e:"人类缺乏尿酸酶(uricase)，嘌呤分解终产物为尿酸。尿酸水平过高(>7mg/dL)可导致痛风和肾结石。别嘌呤醇(黄嘌呤氧化酶抑制剂)用于降尿酸治疗。",r:"《生化》P235",kp:"嘌呤分解",tg:["尿酸","痛风"]}),
Q({id:"biochem-common-040",d:"common",ct:"heal",cn:"胰岛素信号",ec:2,ce:"恢复4点HP",q:"胰岛素受体属于哪类受体？",op:["A. 受体酪氨酸激酶(RTK)","B. G蛋白偶联受体","C. 核受体","D. 离子通道受体"],a:["A"],e:"胰岛素受体是α₂β₂四聚体的RTK，结合胰岛素后自磷酸化激活β亚基的酪氨酸激酶活性，磷酸化IRS1/2，激活PI3K-Akt通路介导代谢效应。",r:"《生化》P270",kp:"胰岛素信号",tg:["胰岛素受体","RTK"]}),

// Continue 41-60
Q({id:"biochem-common-041",d:"common",ct:"attack",cn:"嘧啶合成抑制",ec:2,ce:"造成3点伤害",q:"嘧啶核苷酸从头合成的起始底物组合是？",op:["A. 谷氨酰胺+HCO₃⁻+ATP→氨基甲酰磷酸(CPS-II)","B. 甘氨酸+PRPP","C. 天冬氨酸+PRPP","D. 谷氨酸+NH₃"],a:["A"],e:"嘧啶合成的第一步由CPS-II催化谷氨酰胺+HCO₃⁻+2ATP→氨基甲酰磷酸(胞质中)。不同于尿素循环中的CPS-I(线粒体中、用NH₃、N-乙酰谷氨酸激活)。",r:"《生化》P230",kp:"嘧啶合成",tg:["CPS-II","嘧啶"]}),
Q({id:"biochem-common-042",d:"common",t:"single",ct:"defense",cn:"铁蛋白储存防御",ec:2,ce:"获得4点护盾",q:"铁反应元件结合蛋白(IRE-BP)调控铁蛋白和转铁蛋白受体mRNA的机制涉及？",op:["A. 结合IRE茎环结构调控mRNA稳定性和翻译","B. DNA甲基化","C. 组蛋白乙酰化","D. miRNA调控"],a:["A"],e:"低铁时IRE-BP结合铁蛋白mRNA 5'UTR的IRE抑制翻译，同时结合TfR mRNA 3'UTR的IRE增加其稳定性。高铁时IRE-BP失去结合能力(因Fe-S簇)，铁蛋白翻译增加而TfR mRNA降解。",r:"《生化》P370",kp:"铁代谢调控",tg:["IRE-BP","铁蛋白"]}),
Q({id:"biochem-common-043",d:"common",ct:"attack",cn:"解偶联蛋白产热",ec:2,ce:"造成4点伤害",q:"棕色脂肪组织中UCP1(thermogenin)的生理功能是？",op:["A. 非寒战产热","B. 增加ATP合成","C. 抑制脂肪酸氧化","D. 促进糖酵解"],a:["A"],e:"UCP1在线粒体内膜形成质子通道，使质子回流不经ATP合酶，氧化能量以热能形式释放。受去甲肾上腺素/cAMP/PKA通路和游离脂肪酸激活。",r:"《生化》P135",kp:"非寒战产热",tg:["UCP1","棕色脂肪"]}),
Q({id:"biochem-common-044",d:"common",ct:"heal",cn:"重组修复",ec:2,ce:"恢复3点HP",q:"同源重组修复(HR)主要发生在细胞周期的哪个阶段？",op:["A. S/G2期","B. G1期","C. M期","D. G0期"],a:["A"],e:"HR需要姐妹染色单体作为模板，因此主要在S/G2期活跃。NHEJ可在任何时期发生但易出错。PARP抑制剂选择性杀伤HR缺陷(BRCA1/2突变)肿瘤(合成致死)。",r:"《生化》P320",kp:"DNA修复与细胞周期",tg:["同源重组","细胞周期"]}),
Q({id:"biochem-common-045",d:"common",ct:"attack",cn:"乳糖操纵子模型",ec:2,ce:"造成3点伤害",q:"大肠杆菌lac操纵子中，阻遏蛋白结合在哪个序列上？",op:["A. 操纵基因(operator)","B. 启动子(promoter)","C. CAP结合位点","D. 结构基因"],a:["A"],e:"Lac阻遏蛋白(LacI四聚体)结合在lac操纵基因上阻止RNA聚合酶转录。有乳糖时，别乳糖与阻遏蛋白结合→构象变化→从DNA解离→转录启动。这是原核基因调控的经典模型(1961,Jacob和Monod,1965年诺贝尔奖)。",r:"《生化》P380",kp:"原核基因调控",tg:["lac操纵子","阻遏蛋白"]}),
Q({id:"biochem-common-046",d:"common",ct:"defense",cn:"金属硫蛋白防御",ec:1,ce:"获得2点护盾",q:"金属硫蛋白(metallothionein)富含哪种氨基酸？",op:["A. 半胱氨酸(约30%)","B. 甘氨酸","C. 脯氨酸","D. 谷氨酸"],a:["A"],e:"金属硫蛋白富含Cys(约占30%)，通过硫醇基团结合Zn²⁺、Cu⁺、Cd²⁺等重金属，参与金属离子稳态和解毒。受金属反应元件(MRE)调控。",r:"《生化》P370",kp:"金属硫蛋白",tg:["半胱氨酸","金属解毒"]}),
Q({id:"biochem-common-047",d:"common",ct:"attack",cn:"细胞色素P450解毒",ec:2,ce:"造成4点伤害",q:"肝脏药物代谢中最主要的CYP450酶是？",op:["A. CYP3A4","B. CYP2D6","C. CYP2C9","D. CYP1A2"],a:["A"],e:"CYP3A4是肝脏和肠道中表达量最高的CYP450(约占总量30-40%)，代谢超过50%的临床药物。其表达受PXR核受体调控，底物包括环孢素、他汀类、钙通道阻滞剂等。",r:"《生化》P195",kp:"药物代谢酶",tg:["CYP3A4","药物代谢"]}),
Q({id:"biochem-common-048",d:"common",t:"truefalse",ct:"heal",cn:"分子伴侣修复",ec:1,ce:"恢复2点HP",q:"GroEL/GroES是原核生物的分子伴侣系统，属于Ⅰ型伴侣素(chaperonin)。",op:["A. 正确","B. 错误"],a:["A"],e:"GroEL(14个亚基组装的桶状结构)和GroES(盖状结构)构成原核生物的Ⅰ型伴侣素，提供一个隔离腔帮助蛋白质折叠。真核生物的TCP-1环状复合体(TRiC/CCT)是Ⅱ型伴侣素。",r:"《生化》P360",kp:"分子伴侣",tg:["GroEL","伴侣素"]}),
Q({id:"biochem-common-049",d:"common",ct:"attack",cn:"葡萄糖-丙氨酸循环",ec:2,ce:"造成4点伤害",q:"葡萄糖-丙氨酸循环中，肌肉中丙酮酸经ALT转化为丙氨酸，其氨基来自？",op:["A. 支链氨基酸(BCAA)分解产生的谷氨酸","B. 游离氨","C. 尿素","D. 甘氨酸"],a:["A"],e:"肌肉中BCAA(亮氨酸、异亮氨酸、缬氨酸)分解产生谷氨酸，经ALT将氨基转移给丙酮酸→丙氨酸。丙氨酸经血液运至肝脏→脱氨基→丙酮酸→糖异生→葡萄糖→肌肉(Cahill循环)。",r:"《生化》P210",kp:"氨基酸代谢",tg:["葡萄糖-丙氨酸循环","BCAA"]}),
Q({id:"biochem-common-050",d:"common",ct:"attack",cn:"G蛋白循环",ec:2,ce:"造成3点伤害",q:"G蛋白(Gs)的自发GTP酶活性水解GTP为GDP的时间约为？",op:["A. 数秒至数十秒","B. 数毫秒","C. 数小时","D. 数天"],a:["A"],e:"Gsα内在GTP酶活性约在数秒至数十秒内将GTP水解为GDP，使G蛋白回到非活性状态。此活性受RGS蛋白(G蛋白信号调节蛋白，作为GAP)加速。霍乱毒素ADP-核糖基化Gsα使其GTP酶失活→持续活化→cAMP↑→腹泻。",r:"《生化》P265",kp:"G蛋白循环",tg:["G蛋白","GTP酶"]}),

// 51-60 remaining common
Q({id:"biochem-common-051",d:"common",ct:"heal",cn:"一氧化氮信号",ec:2,ce:"恢复4点HP",q:"一氧化氮(NO)的信号转导机制主要是？",op:["A. 激活可溶性鸟苷酸环化酶(sGC)→cGMP↑","B. 激活腺苷酸环化酶→cAMP↑","C. 直接磷酸化蛋白质","D. 激活磷脂酶C→IP3↑"],a:["A"],e:"NO是气体信号分子，跨膜扩散后结合并激活胞质中的可溶性鸟苷酸环化酶(sGC)的血红素基团，催化GTP→cGMP，cGMP激活PKG导致血管平滑肌舒张。硝酸甘油通过释放NO起效。",r:"《生化》P275",kp:"NO信号",tg:["NO","cGMP"]}),
Q({id:"biochem-common-052",d:"common",ct:"defense",cn:"抗氧化酶系统防御",ec:2,ce:"获得4点护盾",q:"催化两分子超氧阴离子(O₂•⁻)歧化反应的酶是？",op:["A. 超氧化物歧化酶(SOD)","B. 过氧化氢酶","C. 谷胱甘肽过氧化物酶","D. 过氧化物氧还蛋白"],a:["A"],e:"SOD催化:2O₂•⁻+2H⁺→H₂O₂+O₂。三种SOD同工酶:Cu/Zn-SOD(SOD1,胞质)、Mn-SOD(SOD2,线粒体)、EC-SOD(SOD3,胞外)。SOD1突变可致家族性ALS。",r:"《生化》P175",kp:"SOD",tg:["SOD","ALS"]}),
Q({id:"biochem-common-053",d:"common",ct:"attack",cn:"非氧化脱氨",ec:2,ce:"造成3点伤害",q:"直接脱去L-氨基酸的氨基的酶是？",op:["A. L-氨基酸氧化酶","B. ALT转氨酶","C. 谷氨酸脱氢酶","D. 谷氨酰胺酶"],a:["C"],e:"谷氨酸脱氢酶(GDH)是唯一能将氨基酸直接氧化脱氨的酶:谷氨酸+NAD(P)⁺→α-酮戊二酸+NH₄⁺+NAD(P)H。ADP/GDP激活，GTP/ATP抑制。",r:"《生化》P208",kp:"氨基酸氧化脱氨",tg:["谷氨酸脱氢酶","氧化脱氨"]}),
Q({id:"biochem-common-054",d:"common",t:"truefalse",ct:"heal",cn:"DNA甲基化修复",ec:1,ce:"恢复2点HP",q:"CpG岛高甲基化可导致肿瘤抑制基因转录沉默。",op:["A. 正确","B. 错误"],a:["A"],e:"启动子CpG岛高甲基化是表观遗传基因沉默的重要机制，在多种肿瘤中导致p16、MLH1、BRCA1等抑癌基因的失活。DNMT抑制剂(阿扎胞苷、地西他滨)可逆转此类甲基化。",r:"《生化》P400",kp:"DNA甲基化",tg:["CpG岛","表观遗传"]}),
Q({id:"biochem-common-055",d:"common",ct:"attack",cn:"糖蛋白合成",ec:2,ce:"造成3点伤害",q:"N-连接糖基化发生在蛋白质的哪种氨基酸残基上？",op:["A. 天冬酰胺(Asn)的Asn-X-Ser/Thr序列","B. 丝氨酸","C. 苏氨酸","D. 赖氨酸"],a:["A"],e:"N-糖基化发生在Asn-X-Ser/Thr序列(X≠Pro)的Asn残基上。N-糖链在内质网中预装配为G寡糖前体(G3M9)，由寡糖基转移酶(OST)整体转移。O-糖基化在Ser/Thr残基上发生。",r:"《生化》P355",kp:"糖基化",tg:["N-糖基化","Asn"]}),
Q({id:"biochem-common-056",d:"common",ct:"attack",cn:"无氧糖酵解",ec:3,ce:"造成5点伤害",q:"缺氧时无氧糖酵解的终产物乳酸通过哪种穿梭系统转运？",op:["A. MCT(单羧酸转运体)","B. GLUT4","C. Na⁺/K⁺-ATP酶","D. 水通道蛋白"],a:["A"],e:"MCT1-4(单羧酸转运体)介导乳酸和质子的协同转运，MCT4主要在糖酵解组织(白肌纤维)排出乳酸，MCT1在氧化组织(心、红肌)摄入乳酸。肿瘤细胞MCT1/4高表达维持有氧糖酵解。",r:"《生化》P110",kp:"乳酸转运",tg:["MCT","乳酸"]}),
Q({id:"biochem-common-057",d:"common",ct:"defense",cn:"脂联素保护",ec:2,ce:"获得3点护盾",q:"脂肪细胞分泌的脂联素(adiponectin)具有什么效应？",op:["A. 增加胰岛素敏感性","B. 促进食欲","C. 升高血糖","D. 促进脂肪合成"],a:["A"],e:"脂联素通过AdipoR1/R2激活AMPK和PPARα通路，增加骨骼肌脂肪酸氧化和胰岛素敏感性。肥胖者脂联素水平降低，与胰岛素抵抗相关。",r:"《生化》P280",kp:"脂肪因子",tg:["脂联素","胰岛素敏感性"]}),
Q({id:"biochem-common-058",d:"common",ct:"heal",cn:"叶酸循环修复",ec:2,ce:"恢复3点HP",q:"二氢叶酸还原酶(DHFR)抑制剂甲氨蝶呤(MTX)的抗癌机制是？",op:["A. 阻断四氢叶酸再生→抑制核苷酸合成→抑制DNA复制","B. 直接破坏DNA链","C. 抑制拓扑异构酶","D. 交联DNA链"],a:["A"],e:"MTX竞争性抑制DHFR，阻断二氢叶酸(FH₂)→四氢叶酸(FH₄)再生，影响一碳单位转移→抑制dTMP和嘌呤合成→阻断DNA复制→S期特异性杀伤。亚叶酸(leucovorin)用于解救正常细胞。",r:"《生化》P235",kp:"叶酸代谢",tg:["甲氨蝶呤","DHFR"]}),
Q({id:"biochem-common-059",d:"common",ct:"attack",cn:"别嘌呤醇",ec:2,ce:"造成3点伤害",q:"别嘌呤醇(allopurinol)治疗痛风的作用机制是？",op:["A. 抑制黄嘌呤氧化酶(XO)","B. 促进尿酸排泄","C. 抑制尿酸重吸收","D. 降解尿酸"],a:["A"],e:"别嘌呤醇及其代谢产物别嘌呤二醇(oxypurinol)是黄嘌呤氧化酶的竞争性和自杀性抑制剂，阻断次黄嘌呤→黄嘌呤→尿酸，减少尿酸生成。非布索他(febuxostat)是新型非嘌呤类XO抑制剂。",r:"《生化》P238",kp:"嘌呤代谢药物",tg:["别嘌呤醇","黄嘌呤氧化酶"]}),
Q({id:"biochem-common-060",d:"common",ct:"heal",cn:"蛋白质折修复",ec:2,ce:"恢复4点HP",q:"蛋白质二硫键异构酶(PDI)催化什么反应？",op:["A. 蛋白质二硫键的异构化(重排)和形成","B. 肽键形成","C. 磷酸化","D. 泛素化"],a:["A"],e:"PDI在内质网中催化蛋白质二硫键的形成(氧化)和错误二硫键的重排(异构)，帮助蛋白质获得正确构象。PDI被氧化后再生需要Ero1和/或PRDX4传递氧化当量。",r:"《生化》P358",kp:"二硫键形成",tg:["PDI","二硫键"]}),

// ===== Rare (36) =====
Q({id:"biochem-rare-001",d:"rare",t:"single",ct:"attack",cn:"蛋白质组学精准打击",ec:3,ce:"造成7点伤害",q:"泛素分子通过其哪个氨基酸残基与靶蛋白赖氨酸形成异肽键？",op:["A. 甘氨酸76(Gly76)","B. 赖氨酸48(Lys48)","C. 半胱氨酸","D. 丝氨酸"],a:["A"],e:"泛素C端Gly76的羧基与靶蛋白Lys的ε-氨基形成异肽键。K48多聚泛素链(≥4个)是蛋白酶体降解信号，K63链参与信号转导和DNA修复。不同类型的泛素链代表不同的细胞信号。",r:"《生化》P345",kp:"泛素化",tg:["泛素","异肽键"]}),
Q({id:"biochem-rare-002",d:"rare",ct:"defense",cn:"硒蛋白合成防御",ec:3,ce:"获得5点护盾",q:"硒代半胱氨酸(Sec)的掺入依赖哪种特殊RNA结构？",op:["A. SECIS元件(selenocysteine insertion sequence)","B. IRE(铁反应元件)","C. TATA box","D. Shine-Dalgarno序列"],a:["A"],e:"SECIS元件位于硒蛋白mRNA的3'UTR(真核)或紧接UGA密码子下游(原核)，SECIS结合蛋白(SBP2)和Sec特异性延长因子(EFSec)协同将Sec-tRNASᵉᶜ在UGA处掺入肽链。",r:"《生化》P355",kp:"硒代半胱氨酸掺入",tg:["SECIS","Sec"]}),
Q({id:"biochem-rare-003",d:"rare",t:"multiple",ct:"attack",cn:"代谢组学分析",ec:4,ce:"造成9点伤害",q:"AMPK(AMP活化蛋白激酶)激活后促进的代谢通路包括？",op:["A. 脂肪酸氧化","B. 葡萄糖摄取","C. 线粒体生物合成","D. 胆固醇合成"],a:["A","B","C"],e:"AMPK在能量应激(AMP/ATP↑)时激活，开启分解代谢(脂肪酸氧化、葡萄糖摄取、自噬)并关闭合成代谢(脂肪酸/胆固醇/蛋白质合成)。AMPK磷酸化ACC2促进脂肪酸氧化，磷酸化PGC-1α促进线粒体生物合成。AMPK不促进胆固醇合成(相反通过磷酸化HMG-CoA还原酶抑制它)。",r:"《生化》P285",kp:"AMPK信号",tg:["AMPK","能量代谢"]}),
Q({id:"biochem-rare-004",d:"rare",ct:"heal",cn:"蛋白酶体激活修复",ec:3,ce:"恢复5点HP",q:"免疫蛋白酶体中替代β1/β2/β5催化亚基的是？",op:["A. LMP2(β1i)/MECL-1(β2i)/LMP7(β5i)","B. PA28α/PA28β","C. 19S调节颗粒","D. 11S调节颗粒"],a:["A"],e:"IFN-γ诱导免疫蛋白酶体组装，β1i/β2i/β5i取代标准β1/β2/β5亚基，改变切割偏好(偏向疏水和碱性残基后切割)，产生更适合MHC-I呈递的肽段(8-10aa)。LMP2/7基因位于MHC-II基因座内。",r:"《生化》P348",kp:"免疫蛋白酶体",tg:["免疫蛋白酶体","MHC-I"]}),
Q({id:"biochem-rare-005",d:"rare",ct:"attack",cn:"非经典NF-κB通路",ec:3,ce:"造成7点伤害",q:"非经典NF-κB通路中，IKKα被哪种激酶激活？",op:["A. NIK(NF-κB-inducing kinase)","B. IKKβ","C. TAK1","D. MEKK3"],a:["A"],e:"在非经典NF-κB通路中，NIK(也是一种MAP3K)磷酸化激活IKKα，IKKα将p100(结合RelB)加工为p52，p52/RelB二聚体入核。经典通路则通过TNF→TAK1→IKKβ→IκBα磷酸化降解→p65/p50入核。",r:"《生化》P395",kp:"NF-κB信号",tg:["NF-κB","NIK"]}),
Q({id:"biochem-rare-006",d:"rare",ct:"defense",cn:"RNA编辑防御",ec:3,ce:"获得5点护盾",q:"ApoB mRNA编辑酶(APOBEC1)催化C→U脱氨，导致？",op:["A. CAA(谷氨酰胺)→UAA(终止密码子)→ApoB48","B. CAA→UAA→ApoB100延长","C. 蛋白质磷酸化改变","D. mRNA降解加速"],a:["A"],e:"APOBEC1(仅在小肠表达)将ApoB-100 mRNA第6666位C→U脱氨，使CAA(Gln)→UAA(Stop)，产生截短的ApoB48(占ApoB100 N端48%)。ApoB48组装乳糜微粒，ApoB100组装VLDL。这是RNA编辑的经典例子。",r:"《生化》P355",kp:"RNA编辑",tg:["APOBEC","RNA编辑"]}),

// Rare 7-36 abbreviated
Q({id:"biochem-rare-007",d:"rare",ct:"attack",cn:"HIF-1α通路靶向",ec:3,ce:"造成7点伤害",q:"HIF-1α在正常氧浓度下被如何调控？",op:["A. PHD羟化→VHL识别→泛素化降解","B. 被Hsp90稳定","C. 自动磷酸化激活","D. 被SIRT1去乙酰化活化"],a:["A"],e:"正常氧时PHD(脯氨酰羟化酶)将HIF-1α的Pro402/564羟化，VHL E3连接酶识别羟化HIF-1α→泛素化→蛋白酶体降解。缺氧时PHD活性降低→HIF-1α积累→与HIF-1β形成二聚体→结合HRE→诱导VEGF、EPO、GLUT1等。",r:"《生化》P395",kp:"HIF通路",tg:["HIF-1α","VHL"]}),
Q({id:"biochem-rare-008",d:"rare",ct:"heal",cn:"剪接体调控修复",ec:3,ce:"恢复5点HP",q:"前mRNA剪接体中U1 snRNP识别什么序列？",op:["A. 5'剪接位点(GU dinucleotide)","B. 分支点(A残基)","C. 3'剪接位点(AG dinucleotide)","D. 多聚嘧啶序列"],a:["A"],e:"U1 snRNP通过其snRNA的5'序列与5'剪接位点(内含子起始GU)碱基配对，这是剪接体组装的第一步。U2 snRNP识别分支点，U2AF识别3'剪接位点前的嘧啶区域。",r:"《生化》P340",kp:"mRNA剪接",tg:["剪接体","U1 snRNP"]}),
Q({id:"biochem-rare-009",d:"rare",ct:"attack",cn:"组蛋白密码解译",ec:3,ce:"造成6点伤害",q:"组蛋白乙酰化通常导致基因转录？",op:["A. 激活(染色质开放)","B. 抑制(染色质浓缩)","C. 无影响","D. DNA甲基化"],a:["A"],e:"组蛋白乙酰化(HAT催化)中和Lys正电荷→减弱组蛋白-DNA相互作用→染色质松弛→转录因子可接近DNA。HDAC去乙酰化反之→染色质浓缩→转录抑制。",r:"《生化》P400",kp:"组蛋白修饰",tg:["乙酰化","染色质"]}),
Q({id:"biochem-rare-010",d:"rare",t:"single",ct:"defense",cn:"铁死亡防御机制",ec:3,ce:"获得5点护盾",q:"System Xc⁻(胱氨酸/谷氨酸反向转运体)被抑制后导致铁死亡的原因是？",op:["A. 胱氨酸摄取减少→GSH合成受阻→GPX4底物不足→脂质过氧化","B. 谷氨酸蓄积→兴奋性毒性","C. 钙离子内流","D. ATP耗竭"],a:["A"],e:"System Xc⁻(SLC7A11/SLC3A2)介导胱氨酸(胞外)与谷氨酸(胞内)1:1交换。抑制后胱氨酸摄入减少→半胱氨酸(Cys)→GSH→GPX4需要GSH作为还原当量→GPX4失活→脂质过氧化物积累→铁死亡。Erastin通过抑制System Xc⁻诱导铁死亡。",r:"《生化》P176",kp:"铁死亡机制",tg:["铁死亡","System Xc⁻","GPX4"]}),
Q({id:"biochem-rare-011",d:"rare",ct:"attack",cn:"tRNA氨酰化校对",ec:3,ce:"造成6点伤害",q:"氨酰tRNA合成酶的编辑(proofreading)功能的意义是？",op:["A. 纠正错误氨酰化的tRNA，确保翻译保真度","B. 加速tRNA合成","C. 降解多余的氨基酸","D. 修饰tRNA反密码子"],a:["A"],e:"氨酰tRNA合成酶错误率约10⁻⁴-10⁻⁵，但编辑(水解错误氨基酸-AMP或错误氨酰tRNA)可将其降至10⁻⁷-10⁻⁸。IleRS甚至可区分异亮氨酸和缬氨酸(相差一个-CH₂-)。编辑位点(CPI结构域)独立于合成位点。",r:"《生化》P325",kp:"翻译保真度",tg:["氨酰tRNA合成酶","校对"]}),
Q({id:"biochem-rare-012",d:"rare",ct:"attack",cn:"信号肽切除",ec:3,ce:"造成7点伤害",q:"内质网信号肽酶(Signal peptidase)在何处切割信号肽？",op:["A. 粗面内质网腔内","B. 细胞质中","C. 高尔基体内","D. 核内"],a:["A"],e:"信号肽酶(SEC11复合体)位于粗面内质网腔内，在新生肽链转膜过程中或转膜后切割信号肽。切割位点常为Ala-X-Ala↓。信号肽被切割后，成熟蛋白N端释放入内质网腔内。",r:"《生化》P375",kp:"蛋白质靶向",tg:["信号肽酶","内质网"]}),
Q({id:"biochem-rare-013",d:"rare",ct:"defense",cn:"热休克反应保护",ec:3,ce:"获得5点护盾",q:"内质网未折叠蛋白反应中，BiP脱离PERK/IRE1/ATF6的机制是？",op:["A. 未折叠蛋白竞争结合BiP，释放UPR感受器","B. BiP被降解","C. UPR感受器被磷酸化","D. Ca²⁺浓度变化"],a:["A"],e:"正常状态下BiP(GRP78)结合并抑制三个UPR感受器。未折叠蛋白积累时，BiP被「滴定」到未折叠蛋白上，释放PERK/IRE1/ATF6使其激活。这种竞争结合机制确保UPR响应强度与未折叠蛋白负荷成正比。",r:"《生化》P377",kp:"UPR激活机制",tg:["BiP","UPR"]}),
Q({id:"biochem-rare-014",d:"rare",ct:"attack",cn:"G6PD缺乏症溶血",ec:3,ce:"造成7点伤害",q:"G6PD缺乏症患者食用蚕豆后发生溶血的生化机制是？",op:["A. 蚕豆中的蚕豆嘧啶(vicine)→产生自由基→GSH耗竭→红细胞氧化损伤","B. 蚕豆过敏反应","C. 蚕豆直接破坏红细胞膜","D. 免疫复合物沉积"],a:["A"],e:"G6PD缺乏时PPP途径受阻→NADPH减少→GSH无法再生。蚕豆含蚕豆嘧啶(vicine)和香豌豆嘧啶(convicine)，代谢产生自由基使GSH耗竭→血红蛋白氧化变性(Heinz小体)→红细胞膜氧化损伤→血管内溶血。G6PD缺乏症是世界上最常见的酶缺陷病(~4亿人)。",r:"《生化》P175",kp:"G6PD缺乏症",tg:["G6PD","蚕豆病","氧化应激"]}),
Q({id:"biochem-rare-015",d:"rare",ct:"heal",cn:"糖原贮积修复",ec:3,ce:"恢复5点HP",q:"von Gierke病(糖原贮积症Ⅰ型)缺乏的酶是？",op:["A. 葡萄糖-6-磷酸酶","B. 糖原磷酸化酶","C. 分支酶","D. 去分支酶"],a:["A"],e:"GSDⅠa型缺乏G6Pase→肝糖原分解和糖异生产生的G6P不能生成游离葡萄糖→空腹低血糖、乳酸酸中毒、高尿酸血症(次黄嘌呤/尿酸产生增加)、高甘油三酯血症。",r:"《生化》P152",kp:"糖原贮积症",tg:["GSDⅠ","G6Pase"]}),
Q({id:"biochem-rare-016",d:"rare",t:"truefalse",ct:"attack",cn:"circRNA海绵机制",ec:3,ce:"造成6点伤害",q:"环状RNA(circRNA)可通过海绵效应吸附microRNA调控基因表达。",op:["A. 正确","B. 错误"],a:["A"],e:"circRNA通过反向剪接(back-splicing)形成共价闭合环，如CDR1as/ciRS-7含有约70个miR-7结合位点，可有效吸附并抑制miR-7功能。circRNA还可翻译短肽、结合蛋白质调控转录等。",r:"《生化》P410",kp:"非编码RNA",tg:["circRNA","ceRNA"]}),
Q({id:"biochem-rare-017",d:"rare",ct:"attack",cn:"ABC转运体耐药",ec:3,ce:"造成7点伤害",q:"P-糖蛋白(ABCB1/MDR1)利用什么能量驱动药物泵出？",op:["A. ATP水解","B. 质子梯度","C. Na⁺梯度","D. 光能"],a:["A"],e:"P-gp是ABC(ATP-Binding Cassette)转运体超家族成员，每个转运循环水解2个ATP，将多种疏水药物从细胞质或质膜内叶泵出细胞外。P-gp过表达是肿瘤多药耐药的主要机制之一。",r:"《生化》P60",kp:"ABC转运体",tg:["P-gp","MDR"]}),
Q({id:"biochem-rare-018",d:"rare",ct:"defense",cn:"分子伴侣自噬",ec:3,ce:"获得5点护盾",q:"分子伴侣介导的自噬(CMA)底物蛋白含哪种靶向基序？",op:["A. KFERQ样基序","B. LC3相互作用区域(LIR)","C. 泛素化Lys48链","D. PEST序列"],a:["A"],e:"约30%的胞质蛋白含KFERQ样基序，被Hsc70识别后在溶酶体膜上与LAMP-2A单体结合，通过多聚化LAMP-2A形成的通道转运入溶酶体腔降解。CMA在饥饿时上调，选择性降解蛋白质。",r:"《生化》P365",kp:"CMA",tg:["CMA","KFERQ"]}),
Q({id:"biochem-rare-019",d:"rare",ct:"attack",cn:"磷脂酶A2炎症",ec:3,ce:"造成7点伤害",q:"磷脂酶A2(PLA2)催化膜磷脂sn-2位释放哪种脂肪酸？",op:["A. 花生四烯酸( C20:4)","B. 棕榈酸(C16:0)","C. 油酸(C18:1)","D. DHA(C22:6)"],a:["A"],e:"cPLA2特异地从膜磷脂sn-2位释放花生四烯酸，是前列腺素、白三烯等类花生酸(eicosanoid)合成的限速步骤。COX-1/2将AA转化为前列腺素(PGH₂)，5-LOX将AA转化为白三烯。",r:"《生化》P195",kp:"花生四烯酸代谢",tg:["PLA2","花生四烯酸"]}),
Q({id:"biochem-rare-020",d:"rare",ct:"heal",cn:"microRNA沉默修复",ec:3,ce:"恢复5点HP",q:"miRNA通过碱基配对识别靶mRNA的关键区域是？",op:["A. 种子序列(Seed region, 5'端2-8位)","B. 整个miRNA序列","C. 3'端序列","D. 中间环区域"],a:["A"],e:"miRNA的种子序列(5'端第2-8位核苷酸)与靶mRNA 3'UTR完全或部分碱基配对是识别靶标的关键。单个miRNA可调控数百个靶基因，多数情况导致mRNA降解或翻译抑制。",r:"《生化》P410",kp:"miRNA机制",tg:["miRNA","种子序列"]}),

// + 16 more rare questions
Q({id:"biochem-rare-021",d:"rare",ct:"attack",cn:"FXR胆汁酸受体",ec:3,ce:"造成6点伤害",q:"FXR(法尼醇X受体)被胆汁酸激活后诱导哪种蛋白抑制胆汁酸合成？",op:["A. FGF19/15","B. CYP7A1","C. FGF21","D. GCG"],a:["A"],e:"FXR是胆汁酸的核受体，在回肠中激活后诱导FGF19(人)/FGF15(鼠)分泌，FGF15/19经门脉血至肝脏结合FGFR4/β-Klotho，通过JNK/ERK通路抑制CYP7A1表达，实现胆汁酸合成的负反馈调控。",r:"《生化》P280",kp:"胆汁酸反馈调控",tg:["FXR","FGF19","胆汁酸"]}),
Q({id:"biochem-rare-022",d:"rare",ct:"defense",cn:"氧化磷酸化解耦联防御",ec:3,ce:"获得5点护盾",q:"2,4-二硝基苯酚(DNP)的毒性机制是？",op:["A. 质子载体(protonophore)破坏线粒体质子梯度","B. 抑制ATP合酶","C. 阻断电子传递链","D. 抑制TCA循环"],a:["A"],e:"DNP是经典的解耦联剂，作为质子载体在内膜两侧穿梭质子，破坏质子梯度使氧化产生的能量无法驱动ATP合成而以热散发。DNP曾被用作减肥药但因导致高热和死亡被禁用。",r:"《生化》P135",kp:"解耦联剂",tg:["DNP","解耦联"]}),
Q({id:"biochem-rare-023",d:"rare",t:"multiple",ct:"attack",cn:"SREBP通路激活",ec:4,ce:"造成8点伤害",q:"关于SREBP(固醇调节元件结合蛋白)通路正确的是？",op:["A. SREBP前体锚定在内质网膜上","B. 低固醇时SREBP经SCAP转运至高尔基体","C. S1P和S2P蛋白酶在高尔基体切割SREBP释放活性片段","D. SREBP活性片段入核激活靶基因"],a:["A","B","C","D"],e:"SREBP(1a/1c/2)是胆固醇和脂肪酸代谢的主调控因子。SREBP-SCAP-Insig复合体定位于内质网。固醇低时Insig解离，SCAP护送SREBP至高尔基体，被S1P/S2P依次切割释放bHLH结构域→入核→结合SRE→激活LDLR/HMG-CoA还原酶等基因。",r:"《生化》P395",kp:"SREBP通路",tg:["SREBP","胆固醇代谢"]}),
Q({id:"biochem-rare-024",d:"rare",ct:"heal",cn:"线粒体未折蛋白反应",ec:3,ce:"恢复6点HP",q:"线粒体未折叠蛋白反应(UPRmt)在哺乳动物中的关键转录因子是？",op:["A. ATF5(和CHOP)","B. XBP1s","C. HSF1","D. Nrf2"],a:["A"],e:"哺乳动物UPRmt由ATF5(和CHOP/ATF4)介导，线粒体应激时ATF5入核激活线粒体分子伴侣(Hsp60/mtHsp70)和蛋白酶(ClpP, LONP1)基因。秀丽隐杆线虫中则由ATFS-1(含线粒体靶向序列和NLS)直接介导。",r:"《生化》P390",kp:"UPRmt",tg:["UPRmt","ATF5"]}),
Q({id:"biochem-rare-025",d:"rare",ct:"attack",cn:"朊病毒传播",ec:3,ce:"造成7点伤害",q:"朊病毒蛋白(PrP)致病机制的核心是？",op:["A. PrPC(正常α-螺旋)→PrPSc(异常β-折叠)→模板诱导正常PrP转变为致病形式","B. DNA突变导致","C. RNA病毒感染","D. 染色体异常"],a:["A"],e:"PrPSc(β-折叠丰富)作为模板诱导正常PrPC(α-螺旋为主)发生构象转变→聚集形成淀粉样纤维→神经元死亡。这是一种'蛋白质构象病'，不涉及核酸。Prusiner因此提出朊病毒假说(1997年诺奖)。",r:"《生化》P365",kp:"蛋白质错误折叠病",tg:["朊病毒","PrP","构象转变"]}),
Q({id:"biochem-rare-026",d:"rare",ct:"defense",cn:"FOXO转录防御",ec:3,ce:"获得5点护盾",q:"FOXO转录因子被Akt磷酸化后发生什么？",op:["A. 被14-3-3蛋白结合滞留在胞质中","B. 入核促进基因表达","C. 被降解","D. 活化为乙酰转移酶"],a:["A"],e:"胰岛素/IGF-1→PI3K→Akt→磷酸化FOXO(三个位点)→14-3-3结合→核外排→转录活性下降→减少糖异生和抗氧化基因。饥饿时FOXO去磷酸化→入核→激活糖异生、抗氧化和自噬基因，延长寿命。",r:"《生化》P285",kp:"FOXO",tg:["FOXO","Akt","长寿"]}),
Q({id:"biochem-rare-027",d:"rare",ct:"attack",cn:"RNA干扰",ec:3,ce:"造成7点伤害",q:"siRNA在RISC(RNA诱导沉默复合体)中引导哪种核酸酶切割靶mRNA？",op:["A. Ago2(Argonaute2)","B. Dicer","C. Drosha","D. Exportin-5"],a:["A"],e:"Ago2是RISC的核心催化组分，含有PIWI结构域(RNase H样折叠)负责mRNA切割。Ago2在siRNA引导链与靶mRNA完全配对时切割磷酸二酯键(在引导链5'端算起第10-11碱基之间)。Dicer和Drosha分别参与siRNA和miRNA的加工。",r:"《生化》P410",kp:"RNAi机制",tg:["Ago2","RISC"]}),
Q({id:"biochem-rare-028",d:"rare",t:"single",ct:"heal",cn:"核苷酸切除修复",ec:3,ce:"恢复6点HP",q:"人类核苷酸切除修复(NER)中识别损伤的复合体XPC-hHR23B主要识别？",op:["A. 螺旋扭曲损伤(嘧啶二聚体、BPDE加合物等)","B. 单个碱基错配","C. 烷基化损伤","D. 双链断裂"],a:["A"],e:"XPC(与hHR23B/CETN2)通过识别DNA螺旋严重扭曲而非特定化学损伤来启动全局基因组NER(GG-NER)。转录偶联NER(TC-NER)则由RNA Pol II停滞→CSA/CSB介导识别。XP患者NER缺陷→UV高度敏感→皮肤癌风险增加1000倍。",r:"《生化》P318",kp:"NER",tg:["XPC","NER","XP"]}),
Q({id:"biochem-rare-029",d:"rare",ct:"attack",cn:"酮体生成亢进",ec:3,ce:"造成7点伤害",q:"糖尿病酮症酸中毒(DKA)的生化基础是？",op:["A. 胰岛素缺乏→HSL激活→脂肪动员→肝酮体生成速率>外周利用速率","B. 糖酵解过度","C. TCA循环加速","D. 糖异生减弱"],a:["A"],e:"DKA发生机制:胰岛素绝对不足→HSL(激素敏感性脂肪酶)被去抑制→脂肪组织大量释放游离脂肪酸→肝β-氧化和酮体生成急剧增加(HMG-CoA合成酶上调)→超过肝外组织氧化利用能力→酮血症和代谢性酸中毒。",r:"《生化》P165",kp:"酮症酸中毒",tg:["DKA","酮体"]}),
Q({id:"biochem-rare-030",d:"rare",ct:"defense",cn:"Nrf2抗氧化防御",ec:3,ce:"获得5点护盾",q:"Nrf2通路在氧化应激下激活的机制是？",op:["A. Keap1被氧化修饰→Nrf2释放→入核结合ARE→激活抗氧化基因","B. Nrf2被直接磷酸化","C. Nrf2 mRNA稳定化","D. Nrf2从线粒体释放"],a:["A"],e:"正常状态下Keap1(含活性Cys残基)作为E3连接酶接头持续靶向Nrf2泛素化降解。氧化/亲电子应激时Keap1的关键Cys(C151/C273/C288)被修饰→构象变化→Nrf2释放→转位入核→与小Maf形成二聚体→结合ARE→激活GCLC/GCLM/HO-1/NQO1等>200个抗氧化/解毒基因。",r:"《生化》P395",kp:"Nrf2通路",tg:["Nrf2","Keap1"]}),
Q({id:"biochem-rare-031",d:"rare",ct:"attack",cn:"PPARγ脂肪分化",ec:3,ce:"造成6点伤害",q:"PPARγ是哪种药物的靶点？",op:["A. 噻唑烷二酮类(TZDs,如罗格列酮)","B. 他汀类","C. 双胍类(二甲双胍)","D. 胰岛素"],a:["A"],e:"PPARγ是脂肪细胞分化和脂质代谢的主调控因子。TZDs(罗格列酮、吡格列酮)是PPARγ激动剂→促进脂肪生成和脂肪酸储存在脂肪组织→降低循环游离脂肪酸→增加胰岛素敏感性。但罗格列酮因心血管风险受限制。",r:"《生化》P285",kp:"PPARγ",tg:["PPARγ","TZD"]}),
Q({id:"biochem-rare-032",d:"rare",ct:"heal",cn:"铜蓝蛋白修复",ec:3,ce:"恢复5点HP",q:"Wilson病(肝豆状核变性)缺乏哪种蛋白导致铜蓄积？",op:["A. ATP7B(P型铜转运ATP酶)","B. 铜蓝蛋白(Ceruloplasmin)","C. ATP7A","D. 金属硫蛋白"],a:["A"],e:"ATP7B主要在肝脏表达，将铜转运入高尔基体掺入铜蓝蛋白(分泌)或经胆小管排出(胆汁排泄是铜唯一的排出途径)。ATP7B突变→铜在肝脑角膜蓄积→肝病、神经精神症状、Kayser-Fleischer环。治疗:锌剂(诱导金属硫蛋白)、青霉胺(螯合排铜)。ATP7A突变导致Menkes病(铜吸收障碍)。",r:"《生化》P255",kp:"铜代谢",tg:["Wilson病","ATP7B"]}),
Q({id:"biochem-rare-033",d:"rare",ct:"attack",cn:"细胞色素P450诱导",ec:3,ce:"造成7点伤害",q:"芳香烃受体(AhR)被TCDD(二噁英)激活后主要诱导哪种CYP？",op:["A. CYP1A1/1A2/1B1","B. CYP3A4","C. CYP2D6","D. CYP2E1"],a:["A"],e:"AhR是配体激活的bHLH-PAS家族转录因子，与TCDD(二噁英)高亲和力结合→入核与ARNT二聚化→结合XRE(异生物质反应元件)→诱导CYP1家族和UGT/GST等Ⅱ相解毒酶。CYP1A将多环芳烃(PAHs)氧化为致癌二醇环氧化物。",r:"《生化》P395",kp:"AhR信号",tg:["AhR","CYP1A1"]}),
Q({id:"biochem-rare-034",d:"rare",t:"truefalse",ct:"attack",cn:"乙酰化调控代谢",ec:3,ce:"造成6点伤害",q:"SIRT1(NAD⁺依赖性去乙酰化酶)激活可通过去乙酰化PGC-1α促进线粒体生物合成。",op:["A. 正确","B. 错误"],a:["A"],e:"SIRT1是NAD⁺依赖的去乙酰化酶(Ⅲ类HDAC)，在热量限制和NAD⁺升高时激活。SIRT1去乙酰化PGC-1α使其活化→促进线粒体生物合成和脂肪酸氧化。SIRT1还可去乙酰化FOXO/p53/NF-κB等。白藜芦醇是SIRT1的别构激活剂。",r:"《生化》P400",kp:"Sirtuin",tg:["SIRT1","PGC-1α","NAD⁺"]}),
Q({id:"biochem-rare-035",d:"rare",ct:"defense",cn:"甲硫氨酸循环",ec:3,ce:"获得5点护盾",q:"蛋氨酸(甲硫氨酸)循环中，蛋氨酸合酶(MTR)的辅酶是？",op:["A. 甲基钴胺素(MeCbl,维生素B12)","B. 四氢叶酸","C. 磷酸吡哆醛(PLP)","D. FAD"],a:["A"],e:"蛋氨酸合酶催化同型半胱氨酸+5-甲基-THF→蛋氨酸+THF，需要甲基钴胺素(维生素B12的活性形式)作为辅因子。B12缺乏→MTR受阻→同型半胱氨酸升高和5-甲基-THF积累→「叶酸陷阱」→DNA合成受阻→巨幼细胞贫血。",r:"《生化》P215",kp:"蛋氨酸循环",tg:["维生素B12","蛋氨酸合酶"]}),
Q({id:"biochem-rare-036",d:"rare",ct:"heal",cn:"蛋白质去泛素修复",ec:3,ce:"恢复5点HP",q:"去泛素化酶(DUB)中USP家族属于哪类蛋白酶？",op:["A. 半胱氨酸蛋白酶","B. 丝氨酸蛋白酶","C. 金属蛋白酶","D. 天冬氨酸蛋白酶"],a:["A"],e:"DUB共有约100种，分为USP(泛素特异性蛋白酶,半胱氨酸蛋白酶)、UCH(泛素C端水解酶)、OTU(卵巢肿瘤蛋白酶)、MJD(Josephin结构域)和JAMM(金属蛋白酶)五个家族。USP7(HAUSP)去泛素化并稳定p53和MDM2，是抗癌药物靶点。",r:"《生化》P350",kp:"去泛素化",tg:["DUB","USP"]}),

// ===== Epic (18) =====  (abbreviated generation)
Q({id:"biochem-epic-001",d:"epic",t:"single",ct:"attack",cn:"代谢重编程诱导",ec:4,ce:"造成12点伤害",q:"肿瘤细胞中PKM2(丙酮酸激酶M2亚型)的「二聚体形式」如何促进Warburg效应？",op:["A. 二聚体PKM2酶活性低→糖酵解中间产物积累→进入PPP和丝氨酸合成途径","B. 四聚体PKM2活性更高→加速糖酵解","C. PKM2进入线粒体","D. PKM2降解PEP"],a:["A"],e:"PKM2在肿瘤中以低活性二聚体为主(相对于高活性四聚体)，PEP积累导致磷酸甘油酸变位酶(PGAM)被反馈抑制→3PG积累→进入磷酸丝氨酸合成途径(提供一碳单位和核苷酸前体)。同时G6P进入PPP途径产生NADPH和核糖-5-磷酸。这是代谢重编程促进合成代谢的核心机制。PKM2激活剂(TEPP-46)通过促进四聚化抑制肿瘤生长。",r:"《生化》P105",kp:"Warburg效应机制",tg:["PKM2","Warburg效应","代谢重编程"]}),
Q({id:"biochem-epic-002",d:"epic",t:"multiple",ct:"defense",cn:"NAD⁺代谢防御网",ec:5,ce:"获得10点护盾",q:"NAD⁺在细胞中的关键功能包括哪些？",op:["A. 氧化还原辅酶(NAD⁺/NADH)","B. Sirtuin的底物和去乙酰化所需","C. PARP的底物(ADP-核糖来源)","D. CD38的底物(生成cADPR等钙信号分子)","E. 以上全部"],a:["E"],e:"NAD⁺是细胞代谢和信号传导的多功能分子:(1)经典氧化还原辅酶(脱氢酶→NADH→电子传递链)；(2)Sirtuins(7个亚型)用NAD⁺作为共底物去除乙酰基→产生NAM和2'-O-乙酰-ADP核糖；(3)PARP1-17用NAD⁺合成ADP-核糖聚合物(PAR化)；(4)CD38/CD157用NAD⁺生成cADPR(内质网钙释放第二信使)。NAD⁺水平随衰老下降，NAD⁺前体(NMN/NR)补充正在临床试验中。",r:"《生化》P290",kp:"NAD⁺多功能性",tg:["NAD⁺","Sirtuin","PARP"]}),
Q({id:"biochem-epic-003",d:"epic",ct:"attack",cn:"相分离致癌",ec:5,ce:"造成14点伤害",q:"致癌融合蛋白EWS-FLI1(Ewing肉瘤)通过什么机制劫持转录？",op:["A. EWS低复杂结构域(IDR)介导相分离→转录凝聚体形成→异常转录激活","B. 直接结合DNA复制原点","C. 抑制DNA修复","D. 激活Caspase"],a:["A"],e:"EWS-FLI1融合蛋白(染色体t(11;22)易位产生)含EWS的N端低复杂结构域(富含Gln/Gly/Ser/Thr/Tyr)和FLI1的ETS DNA结合结构域。EWS的IDR驱动液-液相分离形成转录凝聚体(含RNA Pol II、MED1、BRD4等)，在GGAA微卫星重复序列处异常激活转录→驱动Ewing肉瘤靶基因表达。这是相分离与肿瘤发生的直接联系。",r:"《生化》P405",kp:"相分离与肿瘤",tg:["EWS-FLI1","相分离","转录凝聚体"]}),
Q({id:"biochem-epic-004",d:"epic",ct:"heal",cn:"分子胶靶向降解",ec:4,ce:"恢复10点HP",q:"来那度胺(lenalidomide)作为分子胶(molecular glue)诱导靶蛋白降解的机制是什么？",op:["A. 改变CRBN(CRL4 E3连接酶底物受体)表面→招募新底物(IKZF1/3)→泛素化降解","B. 直接抑制靶蛋白","C. 激活自噬","D. DNA损伤"],a:["A"],e:"来那度胺等IMiDs结合CRBN(E3泛素连接酶CRL4的底物受体)后→改变其蛋白-蛋白相互作用表面→招募IKZF1(Ikaros)和IKZF3(Aiolos)锌指转录因子→被泛素化→蛋白酶体降解。这代表了PROTAC之外的「分子胶」靶向蛋白降解策略。降解IKZF1/3对多发性骨髓瘤细胞有选择性毒性。",r:"《生化》P350",kp:"靶向蛋白降解",tg:["分子胶","CRBN","PROTAC"]}),

// 5-18 epic (generated compact)
Q({id:"biochem-epic-005",d:"epic",t:"single",ct:"attack",cn:"癌细胞代谢弱点",ec:4,ce:"造成11点伤害",q:"异柠檬酸脱氢酶(IDH1/2)突变(R132H/R140Q)在肿瘤中的'新形态'功能是？",op:["A. 获得催化α-KG→2-HG(2-羟基戊二酸)的新活性","B. 完全丧失酶活性","C. 催化异柠檬酸→柠檬酸","D. 反向催化TCA循环"],a:["A"],e:"IDH1/2热点突变(R132/R140/R172)改变活性位点，使正常催化(异柠檬酸→α-KG)转变为新形态活性(α-KG+NADPH→D-2-HG+NADP⁺)。D-2-HG是「肿瘤代谢物」(oncometabolite)，竞争性抑制α-KG依赖性双加氧酶(包括TET2→DNA高甲基化表型和EGLN→HIF-1α稳定化)。IDH抑制剂(ivosidenib/enasidenib)治疗IDH突变白血病。",r:"《生化》P125",kp:"IDH突变",tg:["IDH","2-HG","肿瘤代谢物"]}),
Q({id:"biochem-epic-006",d:"epic",t:"multiple",ct:"defense",cn:"m⁶A表观转录防御",ec:4,ce:"获得9点护盾",q:"关于m⁶A(N⁶-甲基腺苷)RNA修饰，正确的是？",op:["A. 是mRNA中最丰富的内部修饰","B. METTL3/METTL14复合体催化写入(writer)","C. FTO和ALKBH5是去甲基酶(eraser)","D. YTHDF家族蛋白是阅读蛋白(reader)","E. 以上全部"],a:["E"],e:"m⁶A是mRNA中最常见的内部修饰(~0.1-0.4%的A被修饰)，由METTL3/METTL14/WTAP等writer复合体催化，FTO/ALKBH5可去除(eraser)，YTHDF1-3/YTHDC1-2等reader蛋白识别后调控mRNA剪接、出核、翻译和降解。m⁶A参与干细胞分化、昼夜节律、肿瘤发生等过程。",r:"《生化》P415",kp:"RNA表观转录组",tg:["m⁶A","表观转录组"]}),
Q({id:"biochem-epic-007",d:"epic",ct:"attack",cn:"合成致死精准打击",ec:5,ce:"造成12点伤害",q:"BRCA1/2突变肿瘤对PARP抑制剂敏感的「合成致死」(synthetic lethality)原理是？",op:["A. PARP抑制→单链断裂积累→复制叉遇到未修复SSB→双链断裂→需HR修复→BRCA缺陷细胞HR失能→死亡","B. PARP抑制剂直接杀死BRCA突变细胞","C. PARP激活HR通路","D. PARP抑制免疫系统"],a:["A"],e:"合成致死:两个基因单独突变均可存活，但同时缺陷致死。PARP抑制→BER通路受阻→大量SSB→复制时SSB转为DSB→正常细胞由BRCA1/2介导的HR修复DSB。BRCA突变肿瘤HR缺陷→DSB无法修复→复制灾难和细胞死亡。正常细胞(HR正常)不受影响。PARPi奥拉帕利(olaparib)等已用于BRCA突变卵巢癌/乳腺癌。",r:"《生化》P320",kp:"合成致死",tg:["PARP","BRCA","合成致死"]}),
Q({id:"biochem-epic-008",d:"epic",ct:"heal",cn:"溶酶体信号枢纽修复",ec:4,ce:"恢复9点HP",q:"TFEB(转录因子EB)作为溶酶体生物合成的核心调控因子的激活机制是？",op:["A. mTORC1磷酸化TFEB→滞留在溶酶体表面;饥饿→mTORC1失活→TFEB去磷酸化→入核","B. TFEB持续在核内表达","C. TFEB被Caspase切割激活","D. TFEB经Wnt信号激活"],a:["A"],e:"营养充足时mTORC1在溶酶体表面磷酸化TFEB(Ser211)→14-3-3结合→胞质/溶酶体表面滞留→不能入核。饥饿/溶酶体应激→mTORC1失活→钙调磷酸酶(calcineurin)去磷酸化TFEB→入核→结合CLEAR元件→协同表达溶酶体水解酶、V-ATPase、自噬蛋白等溶酶体-自噬通路全套基因(CLEAR网络)。TFEB是溶酶体功能的核心转录调控节点。",r:"《生化》P390",kp:"TFEB",tg:["TFEB","溶酶体生物合成"]}),
Q({id:"biochem-epic-009",d:"epic",ct:"attack",cn:"代谢产物信号",ec:4,ce:"造成10点伤害",q:"α-酮戊二酸(α-KG)作为信号代谢物，通过抑制哪种酶来调控表观遗传？",op:["A. 作为TET和JmjC结构域去甲基酶的共底物(必需)","B. 抑制DNMT1","C. 抑制HDAC","D. 抑制激酶"],a:["A"],e:"α-KG是α-KG依赖性双加氧酶(包括TET1-3(去甲基化5mC→5hmC等)和含JmjC结构域的组蛋白去甲基酶(KDM2-7))的必需共底物。α-KG→琥珀酸+CO₂的同时氧化目标甲基，因此α-KG水平直接影响DNA和组蛋白甲基化状态。IDH突变产生的D-2-HG或延胡索酸/琥珀酸蓄积可竞争抑制这些酶→导致高度甲基化表型。",r:"《生化》P405",kp:"α-KG信号",tg:["α-KG","TET","表观遗传"]}),
Q({id:"biochem-epic-010",d:"epic",t:"single",ct:"defense",cn:"相分离应激颗粒防御",ec:4,ce:"获得8点护盾",q:"应激颗粒(stress granule)中G3BP1蛋白通过什么结构域驱动液-液相分离？",op:["A. NTF2样结构域+富含精氨酸的IDR(固有无序区)","B. SH3结构域","C. WW结构域","D. PH结构域"],a:["A"],e:"G3BP1经过两个模块驱动相分离:NTF2样结构域介导与RNA的相互作用(通过正电表面结合RNA)，C端富含RGG/RG和酸性氨基酸的IDR提供多价弱相互作用驱动液滴凝聚。G3BP1的磷酸化可调控SG组装/解聚。SG异常与肌萎缩侧索硬化症(ALS)和额颞叶痴呆(FTD)相关。",r:"《生化》P35",kp:"应激颗粒",tg:["G3BP1","相分离","ALS"]}),
Q({id:"biochem-epic-011",d:"epic",ct:"attack",cn:"乙酰辅酶A节律",ec:3,ce:"造成9点伤害",q:"乙酰CoA作为乙酰化底物供体的浓度变化如何影响表观遗传？",op:["A. 胞质和核乙酰CoA→组蛋白乙酰化→染色质开放→基因表达激活","B. 乙酰CoA直接结合DNA","C. 乙酰CoA降解组蛋白","D. 乙酰CoA抑制RNA聚合酶"],a:["A"],e:"乙酰CoA是组蛋白乙酰转移酶(HAT)的乙酰基供体。ACLY(ATP-柠檬酸裂解酶)产生核乙酰CoA池→HAT利用其乙酰化组蛋白→染色质开放→促进转录。ACLY和ACSS2(乙酸→乙酰CoA)的抑制或葡萄糖剥夺可降低组蛋白乙酰化水平。这是代谢状态与表观遗传调控的直接联系(代谢-表观遗传轴)。",r:"《生化》P400",kp:"代谢-表观遗传耦合",tg:["乙酰CoA","组蛋白乙酰化"]}),
Q({id:"biochem-epic-012",d:"epic",ct:"heal",cn:"铁硫簇生物合成",ec:4,ce:"恢复9点HP",q:"人类线粒体铁硫簇(ISC)生物合成途径中，支架蛋白ISCU接受来自什么蛋白的铁和硫？",op:["A. frataxin(FXN,供铁)和NFS1-ISD11(供硫)","B. 铁蛋白和半胱氨酸","C. 转铁蛋白和硫辛酸","D. 铁调素和甲硫氨酸"],a:["A"],e:"线粒体铁硫簇组装:半胱氨酸脱硫酶NFS1(与ISD11)从半胱氨酸提取硫生成过硫化物中间体，Frataxin可能提供铁原子或调控铁硫簇组装。硫和铁在ISCU支架蛋白上组装为[2Fe-2S]簇→经HSPA9-GLRX5等分子伴侣/转运蛋白穿梭→转移至受体蛋白或经ABCb7输出胞质用于胞质铁硫蛋白。FXN突变→Friedreich共济失调(神经系统退行+心肌病)。",r:"《生化》P255",kp:"铁硫簇生物合成",tg:["Frataxin","铁硫簇"]}),
Q({id:"biochem-epic-013",d:"epic",t:"multiple",ct:"attack",cn:"酮体信号新功能",ec:4,ce:"造成10点伤害",q:"β-羟丁酸(βHB)不仅是能源物质，其信号功能包括？",op:["A. 抑制HDAC(Ⅰ/Ⅱa类)→组蛋白高度乙酰化→抗氧化基因表达","B. 结合GPR109A(HCA₂)→抗炎效应","C. 抑制NLRP3炎症小体→减少IL-1β分泌","D. 是某些蛋白质β-羟基丁酰化(PTM)的底物"],a:["A","B","C","D"],e:"βHB是从能量分子到多功能信号分子的范例:(1)HDAC抑制(1-5mM)→Foxo3a等启动子组蛋白H3K9/K14乙酰化→抗氧化基因诱导;(2)GPR109A(HCA₂,烟酸受体)→脂肪细胞/免疫细胞→抗炎;(3)直接抑制NLRP3炎症小体组装→阻断IL-1β/IL-18分泌(机制可能与K⁺外流抑制有关);(4)组蛋白赖氨酸β-羟基丁酰化(Kbhb)是一种新翻译后修饰，与饥饿反应基因调控相关。",r:"《生化》P165",kp:"酮体信号功能",tg:["β-羟丁酸","HDAC抑制"]}),
Q({id:"biochem-epic-014",d:"epic",ct:"defense",cn:"胆汁酸受体防御网",ec:4,ce:"获得8点护盾",q:"FXR/FGF19和TGR5(GPBAR1)构成胆汁酸的两种信号系统，TGR5激活后通过哪种机制产生代谢益处？",op:["A. Gs-cAMP→2型碘甲腺原氨酸脱碘酶(D2)→T4→T3→增加棕色脂肪产热","B. 直接激活胰岛素受体","C. 抑制食欲中枢","D. 促进葡萄糖摄取"],a:["A"],e:"TGR5是胆汁酸的质膜GPCR(Gs偶联)→cAMP↑→在棕色脂肪和骨骼肌中激活D2(碘甲腺原氨酸脱碘酶2)→局部T4→T3转化→增加能量消耗和产热。TGR5还在肠道L细胞中刺激GLP-1分泌(促胰岛素效应)。TGR5双激动剂(INT-777/INT-767等)对NASH和2型糖尿病显示代谢益处。",r:"《生化》P280",kp:"TGR5",tg:["TGR5","胆汁酸信号","D2"]}),
Q({id:"biochem-epic-015",d:"epic",ct:"attack",cn:"自噬精准调控",ec:5,ce:"造成13点伤害",q:"mTORC1调控自噬起始复合体(ULK1/ATG13/FIP200/ATG101)的关键磷酸化位点和效应是？",op:["A. 磷酸化ULK1 Ser757→抑制ULK1活性→阻断自噬","B. 磷酸化ULK1 Ser317/777→激活ULK1","C. mTORC1同时磷酸化ATG13→增强ULK1-ATG13相互作用","D. mTORC1不直接调控自噬"],a:["A"],e:"mTORC1通过直接磷酸化ULK1的Ser757和Ser638抑制其激酶活性→阻止AMPK-ULK1结合→阻断自噬起始。而AMPK在饥饿时磷酸化ULK1的Ser317和Ser777→激活ULK1→启动自噬。AMPK和mTORC1对ULK1的不同位点磷酸化实现了自噬的精密营养调控(mTORC1感知氨基酸,AMPK感知能量)。mTORC1也磷酸化ATG13(Ser258等)→影响ATG13-ATG1(ULK1)相互作用。",r:"《生化》P152",kp:"自噬起始调控",tg:["ULK1","mTORC1","自噬"]}),
Q({id:"biochem-epic-016",d:"epic",ct:"heal",cn:"分泌性自噬选择性修复",ec:4,ce:"恢复9点HP",q:"LC3相关的吞噬作用(LAP)与经典自噬的关键区别在于？",op:["A. LAP直接以含病原/死细胞的吞噬体为靶标，非经典自噬的隔离膜起始","B. LAP不依赖LC3","C. LAP发生在细胞质中","D. LAP与吞噬无关"],a:["A"],e:"LAP不同于经典自噬:TLR/CLR等受体激活后，含吞噬物的吞噬体直接招募LC3-PE(经PI3KC3/RUBCN/UVRAG而非经典的ATG14复合体,且需NOX2产生的ROS)。此过程不需要ULK1/ATG13经典自噬起始复合体。LAP在清除凋亡细胞、病原体和调节免疫应答中有独特功能。LAP缺陷与SLE自身免疫相关。",r:"《生化》P155",kp:"非经典自噬",tg:["LAP","LC3","非经典自噬"]}),
Q({id:"biochem-epic-017",d:"epic",t:"single",ct:"attack",cn:"琥珀酸信号异常",ec:4,ce:"造成10点伤害",q:"伪缺氧假说(pseudohypoxia)中，延胡索酸水合酶(FH)或琥珀酸脱氢酶(SDH)突变后积累的代谢物如何导致HIF-1α稳定？",op:["A. 延胡索酸/琥珀酸积累→竞争抑制PHD(α-KG依赖)→HIF-1α羟化受阻→VHL不能识别→HIF-1α积累","B. 直接磷酸化HIF-1α","C. 增加HIF-1α mRNA表达","D. 抑制HIF降解酶的表达"],a:["A"],e:"SDH和FH分别是TCA循环和延胡索酸→苹果酸转化的酶。功能丧失型突变→琥珀酸/延胡索酸积累→作为α-KG的结构类似物竞争抑制PHD(脯氨酰羟化酶)的活性→HIF-1α的Pro402/564不能被羟化→VHL E3连接酶不能识别→HIF-1α不被降解而积累(即使在正常氧条件下)→持续激活血管生成和糖酵解基因→促进肿瘤(HPRCC/SDH缺陷PGL/PCC等)。这是肿瘤代谢物导致表观遗传和信号通路改变的重要机制。",r:"《生化》P395",kp:"伪缺氧",tg:["SDH","FH","HIF-1α"]}),
Q({id:"biochem-epic-018",d:"epic",t:"multiple",ct:"defense",cn:"p53代谢全能防御",ec:5,ce:"获得10点护盾",q:"p53在代谢调控中的非经典功能包括哪些？",op:["A. 激活TIGAR→抑制糖酵解→促进PPP→增加NADPH","B. 激活SCO2→促进线粒体呼吸","C. 诱导SESN1/2→激活AMPK→抑制mTORC1","D. 抑制脂肪酸合成(转录抑制SREBP1c/FASN)","E. 以上全部"],a:["E"],e:"p53不仅诱导凋亡和细胞周期阻滞，还广泛调控代谢:(1)TIGAR(TP53诱导的糖酵解和凋亡调节因子)→降低F-2,6-BP→抑制PFK-1→糖酵解减缓→PPP增加→NADPH和GSH增加→抗氧化;(2)SCO2→促进细胞色素c氧化酶组装→氧化磷酸化;(3)SESN1/2(Sestrins)→AMPK激活→mTORC1抑制→抑制合成代谢;(4)直接转录抑制FASN和SREBP1c→减少脂肪酸合成;(5)激活CPT1C(脂肪酸氧化)。这些代谢效应与p53的肿瘤抑制功能密切相关。",r:"《生化》P365",kp:"p53代谢功能",tg:["p53","代谢调控"]}),

// ===== Legendary (6) =====
Q({id:"biochem-legend-001",d:"legendary",t:"multiple",ct:"special",cn:"代谢重编程大师",ec:7,ce:"造成25点伤害，敌方全体失去3点MP",q:"肿瘤代谢的6个标志性特征(Hanahan&Weinberg 2022版中新增的'新兴标志')包含代谢重编程。关于肿瘤代谢的Warburg效应及其现代认识，正确的是？",op:["A. 有氧糖酵解为肿瘤提供生物合成前体(核苷酸/氨基酸/脂质)而不仅是ATP","B. PI3K/Akt/mTORC1通路驱动葡萄糖摄取和合成代谢","C. c-Myc驱动谷氨酰胺分解(glutaminolysis)","D. 肿瘤细胞间存在代谢共生(metabolic symbiosis)→乳酸穿梭","E. 以上全部"],a:["E"],e:"肿瘤代谢已经从单纯「ATP产生问题」跃升为「合成代谢+信号调控」范式。关键洞察:(1)Warburg效应提供核苷酸(PPP)、丝氨酸/甘氨酸(一碳单位)、乙酰CoA(脂质膜合成)等生物合成砌块→这是合成代谢驱动的有氧糖酵解;(2)PI3K/Akt→GLUT1膜定位+HK激活→mTORC1→SREBP/Lipin1→脂质合成→细胞生长;(3)MYC驱动谷氨酰胺→α-KG→逆TCA(reductive carboxylation)→柠檬酸→乙酰CoA→脂质→且MYC上调LDHA/PKM2/GLUT1等糖酵解酶;(4)代谢区室化+共生:肿瘤缺氧区糖酵解→乳酸→氧合区经MCT1摄取→乳酸→丙酮酸→TCA(反向Warburg效应)。靶向代谢(Ivosidenib等)已获FDA批准,2-DG/CB-839等在进行临床试验。",r:"《生物化学与分子生物学》第9版 P395-410",kp:"肿瘤代谢重编程",tg:["肿瘤代谢","Warburg效应","代谢标志"]}),
Q({id:"biochem-legend-002",d:"legendary",t:"single",ct:"special",cn:"蛋白质降解精准调控",ec:7,ce:"造成20点伤害，移除目标全部正面状态",q:"PROTAC(靶向蛋白降解嵌合体)技术通过劫持哪种E3连接酶实现靶蛋白的泛素化降解？",op:["A. CRBN或VHL等E3连接酶→泛素化→蛋白酶体降解","B. MDM2 E3连接酶","C. BRCA1 E3连接酶","D. TRAF6 E3连接酶"],a:["A"],e:"PROTAC(Proteolysis Targeting Chimera)是双功能分子:一端结合靶蛋白(POI,protein of interest)，另一端结合E3连接酶(CRBN→沙利度胺衍生物;VHL→VHL配体;IAP→IAP拮抗剂)，中间通过linker连接。PROTAC诱导形成POI-PROTAC-E3三元复合体→POI被泛素化→蛋白酶体降解。与经典抑制剂不同,PROTAC是「事件驱动」(催化量)而非「占位驱动」→可反复使用。POI降解后需重新合成(耗数小时-数天)才能恢复功能,获得更持久的药效。ARV-471(ER PROTAC)和ARV-110(AR PROTAC)等已进入临床试验。2022年BTK PROTAC(NX-2127)报告Ⅰ期结果。这代表了全新治疗范式(化学敲除vs化学抑制)。",r:"《生物化学与分子生物学》第9版 P350-355",kp:"PROTAC技术",tg:["PROTAC","靶向蛋白降解"]}),
Q({id:"biochem-legend-003",d:"legendary",t:"single",ct:"attack",cn:"基因组不稳定诱导",ec:6,ce:"造成18点伤害，本回合目标无法防御",q:"APOBEC3家族胞苷脱氨酶在多种肿瘤中导致特征性突变模式(乳腺癌的'kataegis'突变簇)。APOBEC3A/B异常激活的致癌机制是？",op:["A. A3A/B将胞嘧啶脱氨→尿嘧啶→在ssDNA复制过程中→C→T(C→G)突变→产生kataegis局部超突变","B. APOBEC直接破坏DNA","C. APOBEC激活Ras","D. APOBEC抑制p53翻译"],a:["A"],e:"APOBEC3家族(11种,A3A-H)是抗病毒(胞苷脱氨酶)先天免疫因子,可将ssDNA中的C脱氨→U→DNA复制时U与A配对→C→T(G→A)突变,如果U被UNG切除→碱基切除修复可能产生C→G。多个肿瘤(乳腺癌/膀胱癌/肺癌/头颈癌等50%+)基因组中发现了APOBEC特征性突变模式(TCW→T,W=A/T)。'kataegis'(雷雨)描述局部密集突变簇的现象。APOBEC3A(N端胞质)和APOBEC3B(核定位)是主要致癌驱动,高表达与预后不良和免疫治疗耐药相关。A3B抑制剂研发可能开辟新的肿瘤预防/治疗策略。",r:"《生物化学与分子生物学》第9版 P320-325",kp:"APOBEC突变",tg:["APOBEC","kataegis","突变特征"]}),
Q({id:"biochem-legend-004",d:"legendary",t:"multiple",ct:"heal",cn:"代谢-免疫全能修复",ec:7,ce:"恢复20点HP，我方全体恢复5点MP",q:"免疫检查点阻断(抗PD-1/CTLA-4)治疗应答受肿瘤代谢微环境调控。下列哪些代谢因素影响T细胞抗肿瘤功能？",op:["A. 肿瘤细胞消耗葡萄糖→T细胞糖酵解受限→效应功能减弱","B. 肿瘤产生乳酸→抑制T细胞增殖和细胞因子产生","C. 色氨酸经IDO1代谢为犬尿氨酸→Treg分化→免疫抑制","D. 腺苷(Adenosine)经CD39/CD73轴产生→A2AR受体→抑制T细胞","E. 以上全部"],a:["E"],e:"肿瘤微环境(TME)的代谢性免疫抑制是免疫治疗耐药的关键机制:(1)肿瘤高消耗葡萄糖+T细胞糖酵解受抑→PKM2/ENO1活性降低→IFN-γ产生下降;(2)乳酸→降低T细胞NAD⁺/NADH→抑制GAPDH→糖酵解和效应功能下降→且乳酸通过组蛋白乳酸化(lactylation)修饰促进Treg/M2极化;(3)IDO1(IFN-γ诱导)将色氨酸→犬尿氨酸→色氨酸耗竭+GCN2激酶激活→T细胞停滞+AHR激活→Treg扩增;(4)CD39/CD73(胞外核苷酸酶级联)将ATP→AMP→腺苷→结合免疫细胞A2AR→cAMP↑→多重免疫抑制(抑制T/促进Treg/MDSC)。Epacadostat(IDO1)临床疗效有限,CD73抗体(Oleclumab)+抗PD-L1联合治疗在NSCLC中显示希望,CD39和A2AR拮抗剂处于早期临床。",r:"《生化》P285-295",kp:"免疫代谢",tg:["免疫代谢","IDO","腺苷"]}),
Q({id:"biochem-legend-005",d:"legendary",t:"single",ct:"attack",cn:"朊病毒机制灭绝",ec:7,ce:"造成22点伤害，目标失去所有MP",q:"TDP-43(FUS)等RNA结合蛋白在ALS和FTD中形成胞质包涵体的机制与朊病毒样传播有关。其低复杂结构域(low complexity domain)介导的病理相变特征是？",op:["A. LCD从可逆液滴(liquid droplet)→不可逆淀粉样纤维(hydrogel/amyloid)的相变转变","B. TDP-43直接裂解DNA","C. TDP-43激活Caspase-3","D. 从核内排出的RNA聚合酶"],a:["A"],e:"TDP-43(43kD Tar DNA结合蛋白)是RNA结合蛋白,有两个RRM和C端甘氨酸富集LCD(低复杂结构域)。正常功能:TDP-43通过LCD介导液-液相分离形成应激颗粒→应激解除后分解(可逆)。ALS/FTD病理中:TDP-43突变或持续应激→LCD从功能性液滴→不可逆异常纤维化转变(淀粉样交叉-β折叠)→形成胞质聚集(磷酸化/泛素化TDP-43阳性包涵体)→正常TDP-43核功能丧失(隐外显子包含等)+异常聚集的毒性获得功能→神经元死亡。有证据表明病理性TDP-43可通过类朊病毒方式在细胞间传播(种子-模板聚集)。恢复TDP-43液滴可逆性的小分子(atlastin等)是新兴治疗方向。",r:"《生化》P365-370",kp:"相变病",tg:["TDP-43","相分离","ALS"]}),
Q({id:"biochem-legend-006",d:"legendary",t:"single",ct:"special",cn:"CRISPR碱基编辑奇迹",ec:8,ce:"造成30点伤害，无视所有护盾和防御",question:"David Liu实验室开发的腺嘌呤碱基编辑器(ABE)将A•T转换为G•C，其分子机制依赖哪种酶活性？",options:["A. 进化后的tRNA腺苷脱氨酶(TadA)将腺苷(A)脱氨为肌苷(I)→聚合酶将I读为G","B. 直接将A替换为G","C. Cas9切口酶诱导的HR","D. 胞苷脱氨酶活性"],correctAnswers:["A"],explanation:"ABE的进化历程:大肠杆菌tRNA腺苷脱氨酶(TadA)正常情况下在tRNA反密码子中将A→I(肌苷)脱氨。通过定向进化(七轮→TadA7.10)获得以单链DNA中的dA为底物的高活性。ABE7.10包括:nCas9(D10A切口酶)+TadA7.10-TadA(wt二聚体)。sgRNA引导nCas9结合靶DNA→R环形成→暴露ssDNA→TadA7.10将靶A脱氨→dI(脱氧肌苷)→在后续DNA复制/修复中dI被聚合酶读为G→与dC配对→A•T→G•C碱基替换。编辑窗口一般在protospacer位点4-8(从PAM远端计数)。如2019年ABE8e的编辑效率可达90%以上。ABE可纠正约47%的已知致病点突变(G•C→A•T的反向转换)。ABEmax结合了核定位信号和优化密码子。碱基编辑(both CBE and ABE)避免了DSB和供体模板,在基因治疗单基因病中有巨大前景(如早老症、镰状细胞病临床试验中)。但需警惕旁观者编辑(bystander)和脱氨酶的RNA脱靶。",textbookReference:"《生物化学与分子生物学》第9版 P420-430",knowledgePoint:"碱基编辑技术",tags:["碱基编辑","ABE","TadA"]})
];
})();
