/**
 * 细胞生物学 题目集 — 120题
 * 难度分布: common(60) / rare(36) / epic(18) / legendary(6)
 */
(function() {
  var MediCard = window.MediCard || {};
  MediCard.QuestionBank = MediCard.QuestionBank || {};

  MediCard.QuestionBank['cell-biology'] = [
    // ========== 普通题 (60题) ==========
    {id:"cell-bio-common-001",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"溶酶体攻击",energyCost:1,cardEffect:"造成3点伤害",question:"溶酶体内含多种水解酶，其最适pH值约为？",options:["A. 7.0","B. 5.0","C. 8.0","D. 3.0"],correctAnswers:["B"],explanation:"溶酶体内水解酶在酸性环境(pH约5.0)中活性最高，由溶酶体膜上的H⁺-ATP酶维持酸性环境。",textbookReference:"《医学细胞生物学》第6版 P78",knowledgePoint:"溶酶体结构与功能",tags:["细胞器","酸性水解酶"]},
    {id:"cell-bio-common-002",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"线粒体能量",energyCost:2,cardEffect:"造成4点伤害",question:"线粒体中负责ATP合成的酶复合体是？",options:["A. ATP合酶(复合体V)","B. NADH脱氢酶(复合体I)","C. 细胞色素c氧化酶(复合体IV)","D. 琥珀酸脱氢酶(复合体II)"],correctAnswers:["A"],explanation:"ATP合酶(复合体V)利用质子梯度驱动ADP磷酸化生成ATP，是氧化磷酸化的最后步骤。",textbookReference:"《医学细胞生物学》第6版 P112",knowledgePoint:"线粒体氧化磷酸化",tags:["线粒体","ATP合成"]},
    {id:"cell-bio-common-003",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"细胞膜屏障",energyCost:1,cardEffect:"造成2点伤害",question:"细胞膜的基本骨架结构是？",options:["A. 磷脂双分子层","B. 蛋白质单层","C. 胆固醇晶体","D. 糖蛋白网状结构"],correctAnswers:["A"],explanation:"磷脂双分子层是细胞膜的基本骨架，具有亲水头部向外、疏水尾部向内的排列方式。",textbookReference:"《医学细胞生物学》第6版 P45",knowledgePoint:"细胞膜结构",tags:["细胞膜","磷脂双分子层"]},
    {id:"cell-bio-common-004",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"defense",cardName:"核膜防护",energyCost:1,cardEffect:"获得2点护盾",question:"核膜属于哪种膜系统？",options:["A. 细胞膜","B. 内膜系统","C. 线粒体膜","D. 质膜"],correctAnswers:["B"],explanation:"核膜是内膜系统的一部分，与内质网相连，属于细胞内膜系统。",textbookReference:"《医学细胞生物学》第6版 P156",knowledgePoint:"内膜系统",tags:["核膜","内膜系统"]},
    {id:"cell-bio-common-005",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"核糖体合成",energyCost:2,cardEffect:"造成3点伤害",question:"核糖体大亚基在细胞的哪个部位组装？",options:["A. 核仁","B. 细胞质","C. 线粒体","D. 高尔基体"],correctAnswers:["A"],explanation:"核糖体大亚基和小亚基均在核仁中合成，随后转运至细胞质中组装成完整的核糖体。",textbookReference:"《医学细胞生物学》第6版 P162",knowledgePoint:"核仁功能",tags:["核仁","核糖体"]},

    // ... continuing with more common questions
    {id:"cell-bio-common-006",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"高尔基分选",energyCost:1,cardEffect:"造成2点伤害",question:"高尔基体的主要功能是？",options:["A. 蛋白质修饰与分选","B. DNA复制","C. ATP合成","D. 脂肪酸合成"],correctAnswers:["A"],explanation:"高尔基体负责蛋白质的糖基化、硫酸化等修饰，并将蛋白质分选运输到不同目的地。",textbookReference:"《医学细胞生物学》第6版 P135",knowledgePoint:"高尔基体功能",tags:["高尔基体","蛋白质修饰"]},
    {id:"cell-bio-common-007",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"内质网合成",energyCost:2,cardEffect:"造成3点伤害",question:"粗面内质网与滑面内质网的主要区别是？",options:["A. 粗面内质网表面附着核糖体","B. 粗面内质网更小","C. 滑面内质网不存在于肝细胞","D. 滑面内质网储存DNA"],correctAnswers:["A"],explanation:"粗面内质网表面有核糖体附着，主要参与蛋白质合成；滑面内质网无核糖体，参与脂质合成和解毒。",textbookReference:"《医学细胞生物学》第6版 P125",knowledgePoint:"内质网结构功能",tags:["内质网","蛋白质合成"]},
    {id:"cell-bio-common-008",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"defense",cardName:"细胞骨架支撑",energyCost:1,cardEffect:"获得3点护盾",question:"微管的主要组成蛋白是？",options:["A. α和β微管蛋白","B. 肌动蛋白","C. 角蛋白","D. 胶原蛋白"],correctAnswers:["A"],explanation:"微管由α和β微管蛋白二聚体组装而成，是细胞骨架的重要组成部分。",textbookReference:"《医学细胞生物学》第6版 P198",knowledgePoint:"细胞骨架-微管",tags:["微管","细胞骨架"]},
    {id:"cell-bio-common-009",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"过氧化物酶体",energyCost:1,cardEffect:"造成2点伤害",question:"过氧化物酶体的标志酶是？",options:["A. 过氧化氢酶","B. 酸性磷酸酶","C. 琥珀酸脱氢酶","D. 碱性磷酸酶"],correctAnswers:["A"],explanation:"过氧化氢酶(触酶)是过氧化物酶体的标志酶，能分解H₂O₂为H₂O和O₂。",textbookReference:"《医学细胞生物学》第6版 P148",knowledgePoint:"过氧化物酶体",tags:["过氧化物酶体","过氧化氢酶"]},
    {id:"cell-bio-common-010",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"truefalse",cardType:"heal",cardName:"膜流动性恢复",energyCost:2,cardEffect:"恢复4点HP",question:"胆固醇在细胞膜中的作用是调节膜的流动性。",options:["A. 正确","B. 错误"],correctAnswers:["A"],explanation:"胆固醇插入磷脂分子之间，在高温时限制磷脂运动（降低流动性），在低温时阻止磷脂结晶（增加流动性），起到双向调节作用。",textbookReference:"《医学细胞生物学》第6版 P48",knowledgePoint:"细胞膜成分",tags:["胆固醇","膜流动性"]},

    // More common questions (11-60)
    {id:"cell-bio-common-011",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"主动运输",energyCost:2,cardEffect:"造成3点伤害",question:"Na⁺/K⁺-ATP酶每水解1分子ATP，转运离子的数量是？",options:["A. 3个Na⁺出胞,2个K⁺入胞","B. 2个Na⁺出胞,3个K⁺入胞","C. 1个Na⁺出胞,1个K⁺入胞","D. 3个Na⁺入胞,2个K⁺出胞"],correctAnswers:["A"],explanation:"Na⁺/K⁺-ATP酶每水解1个ATP，将3个Na⁺泵出细胞、2个K⁺泵入细胞。",textbookReference:"《医学细胞生物学》第6版 P55",knowledgePoint:"主动运输",tags:["钠钾泵","主动运输"]},
    {id:"cell-bio-common-012",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"defense",cardName:"紧密连接",energyCost:1,cardEffect:"获得2点护盾",question:"紧密连接(闭锁小带)的主要功能是？",options:["A. 封闭细胞间隙防止物质渗漏","B. 增加细胞表面积","C. 促进细胞分裂","D. 产生ATP"],correctAnswers:["A"],explanation:"紧密连接封闭上皮细胞间隙，形成屏障阻止物质通过细胞间隙自由扩散。",textbookReference:"《医学细胞生物学》第6版 P218",knowledgePoint:"细胞连接",tags:["紧密连接","细胞连接"]},
    {id:"cell-bio-common-013",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"信号转导",energyCost:2,cardEffect:"造成3点伤害",question:"G蛋白偶联受体(GPCR)具有几跨膜结构域？",options:["A. 7次","B. 1次","C. 4次","D. 12次"],correctAnswers:["A"],explanation:"GPCR具有7次跨膜α螺旋结构域，是最大的细胞表面受体家族。",textbookReference:"《医学细胞生物学》第6版 P235",knowledgePoint:"细胞信号转导",tags:["GPCR","信号转导"]},
    {id:"cell-bio-common-014",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"有丝分裂",energyCost:3,cardEffect:"造成5点伤害",question:"有丝分裂过程中，姐妹染色单体分离发生在？",options:["A. 后期","B. 前期","C. 中期","D. 末期"],correctAnswers:["A"],explanation:"后期(anaphase)着丝粒分裂，姐妹染色单体分开，在纺锤丝牵引下移向细胞两极。",textbookReference:"《医学细胞生物学》第6版 P280",knowledgePoint:"有丝分裂",tags:["有丝分裂","细胞周期"]},
    {id:"cell-bio-common-015",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"heal",cardName:"自噬修复",energyCost:2,cardEffect:"恢复3点HP",question:"自噬体的形成需要哪种细胞器参与？",options:["A. 溶酶体","B. 线粒体","C. 高尔基体","D. 核糖体"],correctAnswers:["A"],explanation:"自噬体与溶酶体融合形成自噬溶酶体，由溶酶体酶降解内容物。",textbookReference:"《医学细胞生物学》第6版 P150",knowledgePoint:"自噬",tags:["自噬","溶酶体"]},
    {id:"cell-bio-common-016",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"端粒缩短",energyCost:2,cardEffect:"造成4点伤害",question:"端粒酶的主要功能是？",options:["A. 延长染色体末端的端粒DNA","B. 降解端粒","C. 促进细胞凋亡","D. 合成组蛋白"],correctAnswers:["A"],explanation:"端粒酶以自身RNA为模板合成端粒DNA重复序列，延长端粒长度，与细胞衰老和癌变密切相关。",textbookReference:"《医学细胞生物学》第6版 P310",knowledgePoint:"端粒与端粒酶",tags:["端粒酶","细胞衰老"]},
    {id:"cell-bio-common-017",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"defense",cardName:"细胞外基质",energyCost:1,cardEffect:"获得3点护盾",question:"细胞外基质中最丰富的蛋白质是？",options:["A. 胶原蛋白","B. 弹性蛋白","C. 纤连蛋白","D. 层粘连蛋白"],correctAnswers:["A"],explanation:"胶原蛋白是细胞外基质中含量最丰富的结构蛋白，占人体总蛋白的25%-30%。",textbookReference:"《医学细胞生物学》第6版 P220",knowledgePoint:"细胞外基质",tags:["胶原蛋白","细胞外基质"]},

    // I'll use a structured approach to include more questions
    {id:"cell-bio-common-018",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"凋亡启动",energyCost:2,cardEffect:"造成4点伤害",question:"细胞凋亡的执行者 caspases 是哪一类？",options:["A. Caspase-3,6,7","B. Caspase-8,9,10","C. Caspase-1,4,5","D. Caspase-2,11,12"],correctAnswers:["A"],explanation:"Caspase-3/6/7 是执行型caspases，直接降解细胞结构蛋白和DNA，导致凋亡形态学改变。Caspase-8/9是启动型。",textbookReference:"《医学细胞生物学》第6版 P340",knowledgePoint:"细胞凋亡",tags:["凋亡","caspase"]},
    {id:"cell-bio-common-019",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"heal",cardName:"分子伴侣修复",energyCost:1,cardEffect:"恢复2点HP",question:"内质网中帮助蛋白质正确折叠的分子伴侣是？",options:["A. BiP(GRP78)","B. 泛素","C. 蛋白酶体","D. 溶菌酶"],correctAnswers:["A"],explanation:"BiP(GRP78)是内质网中重要的分子伴侣，识别并结合未折叠蛋白的疏水区域，帮助其正确折叠。",textbookReference:"《医学细胞生物学》第6版 P130",knowledgePoint:"蛋白质折叠",tags:["分子伴侣","内质网"]},
    {id:"cell-bio-common-020",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"truefalse",cardType:"defense",cardName:"间隙连接",energyCost:1,cardEffect:"获得2点护盾",question:"间隙连接允许分子量小于1kD的小分子直接通过。",options:["A. 正确","B. 错误"],correctAnswers:["A"],explanation:"间隙连接由连接子(connexon)构成，允许分子量<1kD的小分子和离子在相邻细胞间直接交换。",textbookReference:"《医学细胞生物学》第6版 P216",knowledgePoint:"间隙连接",tags:["间隙连接","细胞通讯"]},

    // 21-60 common questions
    ...[
      {id:"cell-bio-common-021",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"氧化磷酸化解耦联",energyCost:2,cardEffect:"造成4点伤害",q:"解耦联蛋白(UCP)的作用机制是？",opts:["A. 使质子回流不经ATP合酶，能量以热散发","B. 抑制电子传递链","C. 增加ATP合成效率","D. 阻断三羧酸循环"],ans:["A"],exp:"UCP在线粒体内膜形成质子通道，使质子梯度不经ATP合酶直接回流，氧化能量以热能形式释放，见于棕色脂肪组织。",ref:"《细胞生物学》第5版 P120",kp:"氧化磷酸化解耦联",tags:["UCP","产热"]},
      {id:"cell-bio-common-022",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"受体介导内吞",energyCost:2,cardEffect:"造成3点伤害",q:"LDL通过何种方式进入细胞？",opts:["A. 受体介导的内吞作用","B. 吞噬作用","C. 胞饮作用","D. 被动扩散"],ans:["A"],exp:"低密度脂蛋白(LDL)与细胞膜上的LDL受体结合，通过网格蛋白包被小窝内化进入细胞。",ref:"《细胞生物学》第5版 P175",kp:"受体介导内吞",tags:["内吞","LDL受体"]},
      {id:"cell-bio-common-023",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"defense",cardName:"核定位信号",energyCost:1,cardEffect:"获得2点护盾",q:"蛋白质进入细胞核需要哪种信号？",opts:["A. 核定位信号(NLS)","B. 信号肽","C. KDEL序列","D. 甘露糖-6-磷酸"],ans:["A"],exp:"含核定位信号(NLS)的蛋白质被importin识别，通过核孔复合体主动运输进入细胞核。",ref:"《细胞生物学》第5版 P270",kp:"核质运输",tags:["NLS","核孔复合体"]},
      {id:"cell-bio-common-024",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"heal",cardName:"内质网应激",energyCost:2,cardEffect:"恢复3点HP",q:"未折叠蛋白反应(UPR)的感受器不包括？",opts:["A. mTOR","B. IRE1","C. PERK","D. ATF6"],ans:["A"],exp:"UPR的三个感受器是IRE1、PERK和ATF6。mTOR是营养感受通路的关键激酶，不直接参与UPR。",ref:"《细胞生物学》第5版 P133",kp:"未折叠蛋白反应",tags:["UPR","内质网应激"]},
      {id:"cell-bio-common-025",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"溶酶体贮积",energyCost:2,cardEffect:"造成3点伤害",q:"I-细胞病(Inclusion-cell disease)的分子机制是？",opts:["A. 溶酶体酶缺乏甘露糖-6-磷酸标记","B. 溶酶体膜破裂","C. 过氧化物酶体缺失","D. 线粒体功能障碍"],ans:["A"],exp:"I-细胞病因N-乙酰葡萄糖胺磷酸转移酶缺陷，溶酶体酶无法获得M6P分选信号，被分泌到细胞外。",ref:"《细胞生物学》第5版 P142",kp:"溶酶体贮积症",tags:["I-细胞病","M6P"]},
      {id:"cell-bio-common-026",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"微管组织中心",energyCost:1,cardEffect:"造成2点伤害",q:"动物细胞中主要的微管组织中心(MTOC)是？",opts:["A. 中心体","B. 核仁","C. 高尔基体","D. 线粒体"],ans:["A"],exp:"中心体含一对中心粒及其周围的基质(pericentriolar material)，是动物细胞中主要的微管组织中心。",ref:"《细胞生物学》第5版 P205",kp:"微管组织中心",tags:["中心体","MTOC"]},
      {id:"cell-bio-common-027",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"defense",cardName:"选择素黏附",energyCost:1,cardEffect:"获得2点护盾",q:"白细胞渗出血管时首先与内皮细胞的哪种黏附分子作用？",opts:["A. 选择素(Selectin)","B. 整合素(Integrin)","C. 钙黏素(Cadherin)","D. 免疫球蛋白超家族"],ans:["A"],exp:"选择素介导白细胞与内皮细胞的初始接触和滚动，随后整合素介导牢固黏附和穿出。",ref:"《细胞生物学》第5版 P230",kp:"细胞黏附",tags:["选择素","炎症"]},
      {id:"cell-bio-common-028",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"泛素化降解",energyCost:2,cardEffect:"造成3点伤害",q:"泛素-蛋白酶体途径降解的蛋白质首先需要哪种修饰？",opts:["A. 泛素化(多聚泛素链连接)","B. 磷酸化","C. 乙酰化","D. 糖基化"],ans:["A"],exp:"目标蛋白通过E1-E2-E3级联反应被连接多聚泛素链(K48)，被26S蛋白酶体识别并降解。",ref:"《细胞生物学》第5版 P340",kp:"蛋白质降解",tags:["泛素","蛋白酶体"]},
      {id:"cell-bio-common-029",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"truefalse",cardType:"heal",cardName:"膜修复",energyCost:2,cardEffect:"恢复3点HP",q:"细胞膜的流动性主要取决于磷脂分子的侧向扩散运动。",opts:["A. 正确","B. 错误"],ans:["A"],exp:"磷脂分子在膜平面内可自由侧向扩散，而翻转运动极少发生，这是膜流动性的主要表现。",ref:"《细胞生物学》第5版 P46",kp:"膜流动性",tags:["膜流动性","磷脂"]},
      {id:"cell-bio-common-030",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"线粒体DNA突变",energyCost:2,cardEffect:"造成4点伤害",q:"线粒体DNA的遗传方式为？",opts:["A. 母系遗传","B. 父系遗传","C. 双亲遗传","D. 随机遗传"],ans:["A"],exp:"受精卵中线粒体几乎全部来自卵细胞，因此线粒体DNA呈母系遗传。",ref:"《细胞生物学》第5版 P115",kp:"线粒体遗传",tags:["线粒体DNA","母系遗传"]},
      {id:"cell-bio-common-031",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"PI3K-Akt通路",energyCost:3,cardEffect:"造成5点伤害",q:"PI3K/Akt信号通路的主要功能不包括？",opts:["A. 促进细胞凋亡","B. 促进细胞存活","C. 促进细胞生长","D. 调节代谢"],ans:["A"],exp:"PI3K/Akt通路主要通过磷酸化Bad、Caspase-9等底物来抑制凋亡、促进细胞存活和生长，不是促进凋亡。",ref:"《细胞生物学》第5版 P250",kp:"细胞信号通路",tags:["PI3K","Akt"]},
      {id:"cell-bio-common-032",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"defense",cardName:"半桥粒连接",energyCost:1,cardEffect:"获得3点护盾",q:"半桥粒将上皮细胞连接到？",opts:["A. 基底膜","B. 相邻细胞","C. 血管","D. 神经末梢"],ans:["A"],exp:"半桥粒通过整合素α6β4连接细胞角蛋白中间丝与基底膜的层粘连蛋白。",ref:"《细胞生物学》第5版 P222",kp:"细胞连接",tags:["半桥粒","基底膜"]},
      {id:"cell-bio-common-033",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"cAMP信号",energyCost:2,cardEffect:"造成3点伤害",q:"腺苷酸环化酶催化ATP生成？",opts:["A. cAMP","B. cGMP","C. AMP","D. ADP"],ans:["A"],exp:"腺苷酸环化酶(AC)催化ATP环化生成cAMP(第二信使)，激活PKA信号通路。",ref:"《细胞生物学》第5版 P238",kp:"第二信使",tags:["cAMP","腺苷酸环化酶"]},
      {id:"cell-bio-common-034",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"heal",cardName:"SERCA钙泵修复",energyCost:2,cardEffect:"恢复3点HP",q:"肌质网上的钙泵(SERCA)将Ca²⁺泵入？",opts:["A. 肌质网内","B. 细胞外","C. 线粒体内","D. 细胞核内"],ans:["A"],exp:"SERCA(Sarco/Endoplasmic Reticulum Ca²⁺-ATPase)将胞质Ca²⁺泵入肌质网/内质网内储存。",ref:"《细胞生物学》第5版 P260",kp:"钙信号",tags:["SERCA","钙泵"]},
      {id:"cell-bio-common-035",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"初级纤毛缺陷",energyCost:2,cardEffect:"造成3点伤害",q:"初级纤毛的组装依赖于哪种运输系统？",opts:["A. 纤毛内运输(IFT)","B. 囊泡运输","C. 核质运输","D. 线粒体运输"],ans:["A"],exp:"纤毛内运输(IFT)系统沿微管双向运输纤毛组装所需蛋白，IFT缺陷导致多种纤毛病。",ref:"《细胞生物学》第5版 P210",kp:"初级纤毛",tags:["纤毛","IFT"]},

      // More questions 36-60
      {id:"cell-bio-common-036",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"MAPK级联",energyCost:3,cardEffect:"造成5点伤害",q:"Ras-MAPK信号通路中，Ras激活的下游激酶是？",opts:["A. Raf","B. MEK","C. ERK","D. PI3K"],ans:["A"],exp:"Ras-GTP首先结合并激活Raf(MAPKKK)，然后Raf磷酸化MEK(MAPKK)，MEK再磷酸化ERK(MAPK)。",ref:"《细胞生物学》第5版 P248",kp:"MAPK通路",tags:["Ras","MAPK"]},
      {id:"cell-bio-common-037",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"defense",cardName:"抗氧化防御",energyCost:1,cardEffect:"获得2点护盾",q:"细胞内主要的抗氧化剂是？",opts:["A. 谷胱甘肽(GSH)","B. 维生素C","C. 维生素E","D. 辅酶Q10"],ans:["A"],exp:"谷胱甘肽(GSH)是细胞内含量最丰富的非蛋白硫醇，是细胞内最重要的抗氧化剂。",ref:"《细胞生物学》第5版 P95",kp:"氧化应激",tags:["谷胱甘肽","抗氧化"]},
      {id:"cell-bio-common-038",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"truefalse",cardType:"heal",cardName:"膜不对称恢复",energyCost:1,cardEffect:"恢复2点HP",q:"磷脂酰丝氨酸(PS)在正常细胞中主要分布于细胞膜内叶。",opts:["A. 正确","B. 错误"],ans:["A"],exp:"正常细胞维持磷脂不对称分布：PS和PE分布于膜内叶，PC和SM分布于膜外叶。PS外翻是凋亡信号。",ref:"《细胞生物学》第5版 P49",kp:"膜不对称性",tags:["磷脂酰丝氨酸","膜不对称"]},
      {id:"cell-bio-common-039",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"JAK-STAT信号",energyCost:2,cardEffect:"造成4点伤害",q:"JAK-STAT通路的激活步骤正确的是？",opts:["A. 细胞因子→受体二聚化→JAK磷酸化→STAT磷酸化→STAT入核","B. STAT入核→JAK磷酸化→受体二聚化→细胞因子释放","C. JAK磷酸化→细胞因子→STAT入核→受体二聚化","D. 受体二聚化→STAT入核→JAK磷酸化→细胞因子"],ans:["A"],exp:"细胞因子结合受体引起受体二聚化，激活JAK激酶，JAK磷酸化STAT使其二聚化入核调控基因表达。",ref:"《细胞生物学》第5版 P252",kp:"JAK-STAT通路",tags:["JAK","STAT"]},
      {id:"cell-bio-common-040",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"defense",cardName:"细胞周期检查点",energyCost:2,cardEffect:"获得3点护盾",q:"G1/S检查点主要检查什么？",opts:["A. DNA是否损伤","B. 纺锤体是否组装","C. 染色体是否分离","D. 细胞大小"],ans:["A"],exp:"G1/S检查点（R点）检查DNA完整性、细胞大小和营养条件,p53蛋白在此检查点发挥关键作用。",ref:"《细胞生物学》第5版 P290",kp:"细胞周期检查点",tags:["G1/S检查点","p53"]},
      {id:"cell-bio-common-041",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"死亡受体凋亡",energyCost:2,cardEffect:"造成4点伤害",q:"Fas配体结合Fas受体后，招募哪种接头蛋白？",opts:["A. FADD","B. TRADD","C. RIP","D. TRAF2"],ans:["A"],exp:"Fas(CD95)与FasL结合后，通过死亡结构域(DD)招募FADD，FADD再通过DED结构域招募Caspase-8形成DISC。",ref:"《细胞生物学》第5版 P342",kp:"死亡受体通路",tags:["Fas","FADD"]},
      {id:"cell-bio-common-042",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"heal",cardName:"DNA修复",energyCost:2,cardEffect:"恢复3点HP",q:"核苷酸切除修复(NER)主要修复哪种DNA损伤？",opts:["A. 紫外线引起的嘧啶二聚体","B. 单碱基错配","C. 双链断裂","D. 烷基化损伤"],ans:["A"],exp:"NER主要修复UV引起的嘧啶二聚体和大的化学加合物，着色性干皮病(XP)即由NER缺陷引起。",ref:"《细胞生物学》第5版 P310",kp:"DNA修复",tags:["NER","DNA修复"]},
      {id:"cell-bio-common-043",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"Warburg效应",energyCost:2,cardEffect:"造成4点伤害",q:"Warburg效应是指肿瘤细胞即使在有氧条件下也主要进行？",opts:["A. 糖酵解","B. 氧化磷酸化","C. 脂肪酸氧化","D. 氨基酸分解"],ans:["A"],exp:"Warburg效应(有氧糖酵解)是肿瘤细胞的代谢特征，即使氧气充足也优先进行糖酵解产生乳酸。",ref:"《细胞生物学》第5版 P380",kp:"肿瘤细胞代谢",tags:["Warburg效应","糖酵解"]},
      {id:"cell-bio-common-044",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"defense",cardName:"ABC转运蛋白",energyCost:2,cardEffect:"获得3点护盾",q:"多药耐药(MDR)相关的转运蛋白属于哪一超家族？",opts:["A. ABC超家族","B. SLC超家族","C. GPCR超家族","D. 离子通道超家族"],ans:["A"],exp:"P-糖蛋白(MDR1/ABCB1)属于ABC超家族，利用ATP水解能量将药物泵出细胞，导致多药耐药。",ref:"《细胞生物学》第5版 P60",kp:"膜转运蛋白",tags:["MDR","ABC转运蛋白"]},
      {id:"cell-bio-common-045",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"溶酶体释放",energyCost:2,cardEffect:"造成4点伤害",q:"溶酶体酶在何pH条件下活性最高？",opts:["A. pH 4.5-5.0","B. pH 7.0-7.4","C. pH 8.0-8.5","D. pH 6.0-6.5"],ans:["A"],exp:"溶酶体水解酶的最适pH为4.5-5.0（酸性），与溶酶体腔内环境一致。若释放到胞质(pH7.2)则活性大大降低。",ref:"《细胞生物学》第5版 P138",kp:"溶酶体酶",tags:["溶酶体","pH"]},
      {id:"cell-bio-common-046",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"heal",cardName:"ERAD系统",energyCost:2,cardEffect:"恢复3点HP",q:"内质网相关降解(ERAD)将错误折叠蛋白转运至？",opts:["A. 胞质蛋白酶体降解","B. 溶酶体降解","C. 高尔基体修饰","D. 细胞外分泌"],ans:["A"],exp:"ERAD将内质网中错误折叠蛋白逆向转运( dislocation )到胞质，经泛素化后被蛋白酶体降解。",ref:"《细胞生物学》第5版 P134",kp:"ERAD",tags:["ERAD","蛋白质质量控制"]},
      {id:"cell-bio-common-047",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"truefalse",cardType:"defense",cardName:"细胞极性",energyCost:1,cardEffect:"获得2点护盾",q:"上皮细胞的顶端面和基底面表达的蛋白质种类完全相同。",opts:["A. 正确","B. 错误"],ans:["B"],exp:"上皮细胞具有明显的极性，顶端面和基底侧面表达不同的蛋白质和脂质，由紧密连接维持这种极性。",ref:"《细胞生物学》第5版 P218",kp:"上皮细胞极性",tags:["细胞极性","上皮细胞"]},
      {id:"cell-bio-common-048",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"TGF-β信号",energyCost:2,cardEffect:"造成4点伤害",q:"TGF-β信号通路中，受体激活后磷酸化哪种转录因子？",opts:["A. Smad2/3","B. STAT1/2","C. NF-κB","D. β-catenin"],ans:["A"],exp:"TGF-β结合受体后，活化的受体磷酸化R-Smad(Smad2/3)，与Smad4形成复合物入核调控基因转录。",ref:"《细胞生物学》第5版 P256",kp:"TGF-β信号",tags:["TGF-β","Smad"]},
      {id:"cell-bio-common-049",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"动力蛋白运输",energyCost:2,cardEffect:"造成4点伤害",q:"驱动蛋白(kinesin)沿微管向哪个方向运输货物？",opts:["A. 向微管正端(+)","B. 向微管负端(-)","C. 双向运输","D. 无方向性"],ans:["A"],exp:"大多数kinesin向微管正端运输（通常向细胞外周），而dynein向微管负端运输（通常向细胞中心）。",ref:"《细胞生物学》第5版 P207",kp:"分子马达",tags:["kinesin","微管运输"]},
      {id:"cell-bio-common-050",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"defense",cardName:"抗氧化酶系统",energyCost:2,cardEffect:"获得3点护盾",q:"超氧化物歧化酶(SOD)催化什么反应？",opts:["A. 2O₂•⁻ + 2H⁺ → H₂O₂ + O₂","B. H₂O₂ → H₂O + O₂","C. O₂ → O₂•⁻","D. H₂O → OH•"],ans:["A"],exp:"SOD将超氧阴离子(O₂•⁻)转化为H₂O₂，随后由过氧化氢酶或谷胱甘肽过氧化物酶进一步分解。",ref:"《细胞生物学》第5版 P96",kp:"活性氧清除",tags:["SOD","氧化应激"]},

      {id:"cell-bio-common-051",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"Notch信号",energyCost:2,cardEffect:"造成4点伤害",q:"Notch受体激活后，其胞内结构域(NICD)的作用是？",opts:["A. 进入细胞核作为转录共激活因子","B. 留在胞质激活激酶级联","C. 结合细胞骨架","D. 激活G蛋白"],ans:["A"],exp:"Notch经γ-分泌酶切割后释放NICD，直接入核与CSL/RBP-Jκ结合，激活靶基因转录。",ref:"《细胞生物学》第5版 P258",kp:"Notch信号",tags:["Notch","γ-分泌酶"]},
      {id:"cell-bio-common-052",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"heal",cardName:"分子开关GTPase",energyCost:1,cardEffect:"恢复3点HP",q:"小G蛋白Ras的活性形式是？",opts:["A. Ras-GTP","B. Ras-GDP","C. Ras-ATP","D. Ras-ADP"],ans:["A"],exp:"Ras是分子开关蛋白，GTP结合形式为活性状态，GDP结合形式为非活性状态。GAP促进GTP水解使其失活,GEF促进GDP/GTP交换使其活化。",ref:"《细胞生物学》第5版 P244",kp:"小G蛋白",tags:["Ras","GTPase"]},
      {id:"cell-bio-common-053",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"defense",cardName:"紧密连接屏障",energyCost:1,cardEffect:"获得2点护盾",q:"紧密连接中主要的跨膜黏附蛋白是？",opts:["A. Claudin和Occludin","B. Cadherin","C. Integrin","D. Selectin"],ans:["A"],exp:"Claudin和Occludin是紧密连接的主要跨膜蛋白，形成细胞旁屏障。不同Claudin亚型决定通透选择性。",ref:"《细胞生物学》第5版 P218",kp:"紧密连接蛋白",tags:["Claudin","紧密连接"]},
      {id:"cell-bio-common-054",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"染色体端粒",energyCost:2,cardEffect:"造成3点伤害",q:"人类端粒酶的RNA模板序列是？",opts:["A. 5'-CUAACCCUAAC-3'","B. 5'-AUGCGAUGCG-3'","C. 5'-GCAUUGCAUU-3'","D. 5'-UAGGCUAGGC-3'"],ans:["A"],exp:"端粒酶RNA(hTR)含有与端粒重复序列(TTAGGG)互补的模板序列(CCCUAA的互补链是GGGAUU)。",ref:"《细胞生物学》第5版 P312",kp:"端粒酶结构",tags:["端粒酶","hTR"]},
      {id:"cell-bio-common-055",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"truefalse",cardType:"heal",cardName:"伴侣介导自噬",energyCost:1,cardEffect:"恢复2点HP",q:"分子伴侣Hsc70介导的自噬仅降解含KFERQ序列的蛋白质。",opts:["A. 正确","B. 错误"],ans:["A"],exp:"伴侣介导的自噬(CMA)中，Hsc70识别含KFERQ基序的蛋白，将其靶向溶酶体膜上的LAMP-2A受体进行降解。",ref:"《细胞生物学》第5版 P152",kp:"伴侣介导自噬",tags:["CMA","KFERQ"]},
      {id:"cell-bio-common-056",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"Hedgehog信号",energyCost:3,cardEffect:"造成5点伤害",q:"Hedgehog信号通路中，受体Patched对Smoothened的作用是？",opts:["A. 抑制Smo的活性","B. 激活Smo","C. 降解Smo","D. 修饰Smo"],ans:["A"],exp:"在无Hh配体时，Ptch抑制Smo活性。Hh结合Ptch解除抑制，Smo活化引发Gli转录因子激活。",ref:"《细胞生物学》第5版 P260",kp:"Hedgehog信号",tags:["Hedgehog","Smo"]},
      {id:"cell-bio-common-057",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"defense",cardName:"层粘连蛋白",energyCost:2,cardEffect:"获得3点护盾",q:"基底膜中含量最丰富的糖蛋白是？",opts:["A. 层粘连蛋白(Laminin)","B. 纤连蛋白(Fibronectin)","C. IV型胶原","D. 巢蛋白(Nidogen)"],ans:["C"],exp:"IV型胶原形成基底膜的网状骨架结构，是基底膜最丰富的蛋白质，其突变导致Alport综合征。",ref:"《细胞生物学》第5版 P225",kp:"基底膜",tags:["IV型胶原","基底膜"]},
      {id:"cell-bio-common-058",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"线粒体渗透性",energyCost:2,cardEffect:"造成4点伤害",q:"线粒体通透性转换孔(mPTP)开放导致？",opts:["A. 细胞色素c释放→凋亡","B. ATP合成增加","C. 蛋白质合成增加","D. DNA复制加速"],ans:["A"],exp:"mPTP开放使线粒体外膜通透性增加，释放细胞色素c等凋亡因子，激活caspase级联导致凋亡。",ref:"《细胞生物学》第5版 P345",kp:"线粒体凋亡途径",tags:["mPTP","细胞色素c"]},
      {id:"cell-bio-common-059",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"heal",cardName:"蛋白酶体恢复",energyCost:2,cardEffect:"恢复3点HP",q:"26S蛋白酶体的催化核心是？",opts:["A. 20S核心颗粒","B. 19S调节颗粒","C. 11S调节颗粒","D. PA28α"],ans:["A"],exp:"26S蛋白酶体由20S核心颗粒(催化亚基)和19S调节颗粒组成，19S识别泛素化底物并去折叠后送入20S降解。",ref:"《细胞生物学》第5版 P340",kp:"蛋白酶体",tags:["20S","26S蛋白酶体"]},
      {id:"cell-bio-common-060",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"common",questionType:"single",cardType:"attack",cardName:"EMT转化",energyCost:3,cardEffect:"造成5点伤害",q:"上皮-间充质转化(EMT)中下调的标志物是？",opts:["A. E-钙黏素(E-cadherin)","B. N-钙黏素(N-cadherin)","C. 波形蛋白(Vimentin)","D. 纤连蛋白(Fibronectin)"],ans:["A"],exp:"EMT过程中E-cadherin表达下调(上皮标志丧失)，N-cadherin、Vimentin等间充质标志物上调。Snail/Twist等转录因子抑制E-cadherin。",ref:"《细胞生物学》第5版 P390",kp:"EMT",tags:["EMT","E-cadherin"]}
    ].map(function(o){return {id:o.id,subject:o.subject,subjectId:o.subjectId,difficulty:o.difficulty,questionType:o.questionType,cardType:o.cardType,cardName:o.cardName,energyCost:o.energyCost,cardEffect:o.cardEffect,question:o.q,options:o.opts,correctAnswers:o.ans,explanation:o.exp,textbookReference:o.ref,knowledgePoint:o.kp,tags:o.tags};}),

    // ========== 稀有题 (36题) ==========
    ...[
      {id:"cell-bio-rare-001",diff:"rare",qt:"single",ct:"attack",cn:"线粒体融合裂变失衡",ec:2,ce:"造成6点伤害",q:"线粒体融合主要由哪种GTPase介导？",opts:["A. MFN1/MFN2(外膜)和OPA1(内膜)","B. DRP1","C. FIS1","D. DNM1L"],ans:["A"],exp:"MFN1/2介导线粒体外膜融合，OPA1介导内膜融合。DRP1和FIS1介导线粒体分裂。",ref:"《细胞生物学》第5版 P118",kp:"线粒体动力学",tags:["线粒体融合","MFN"]},
      {id:"cell-bio-rare-002",diff:"rare",qt:"single",ct:"defense",cn:"核纤层支撑",ec:2,ce:"获得4点护盾",q:"核纤层(Lamin)的磷酸化导致什么结果？",opts:["A. 核膜在有丝分裂前期崩解","B. 核膜增厚","C. DNA复制","D. 蛋白质合成增加"],ans:["A"],exp:"CDK1/Cyclin B磷酸化核纤层蛋白，引起核纤层解聚，导致核膜在前期崩解。",ref:"《细胞生物学》第5版 P275",kp:"核纤层",tags:["核纤层","有丝分裂"]},
      {id:"cell-bio-rare-003",diff:"rare",qt:"single",ct:"attack",cn:"内质网-线粒体接触",ec:3,ce:"造成7点伤害",q:"内质网-线粒体接触点(MAM)的主要功能不包括？",opts:["A. DNA复制","B. Ca²⁺转运","C. 磷脂合成","D. 线粒体分裂位点标记"],ans:["A"],exp:"MAM是内质网和线粒体的紧密接触区域，参与Ca²⁺信号转导、磷脂(PS/PE/PC)合成以及线粒体分裂位点的标记，不参与DNA复制。",ref:"《细胞生物学》第5版 P122",kp:"MAM",tags:["MAM","线粒体-内质网接触"]},
      {id:"cell-bio-rare-004",diff:"rare",qt:"single",ct:"heal",cn:"SNARE复合体修复",ec:2,ce:"恢复5点HP",q:"突触囊泡与突触前膜融合依赖的SNARE蛋白组合是？",opts:["A. Synaptobrevin+Syntaxin+SNAP-25","B. Synaptobrevin+Syntaxin+SNAP-23","C. VAMP8+Syntaxin7+SNAP-29","D. VAMP7+Syntaxin3+SNAP-23"],ans:["A"],exp:"突触囊泡上的Synaptobrevin(VAMP2)与突触前膜的Syntaxin和SNAP-25形成SNARE复合体，介导Ca²⁺触发的快速胞吐。",ref:"《细胞生物学》第5版 P180",kp:"SNARE介导膜融合",tags:["SNARE","突触传递"]},
      {id:"cell-bio-rare-005",diff:"rare",qt:"multiple",ct:"attack",cn:"多聚ADP-核糖化",ec:2,ce:"造成6点伤害",q:"关于PARP在DNA损伤反应中的作用，正确的是？",opts:["A. PARP1识别DNA单链断裂","B. PARP催化合成PAR链","C. PARP过度激活消耗NAD⁺","D. PARP直接修复DNA缺口"],ans:["A","B","C"],exp:"PARP1识别并结合DNA单链断裂，催化合成多聚ADP核糖(PAR)链招募修复蛋白。过度激活导致NAD⁺耗竭和ATP危机，可触发坏死(parthanatos)。PARP不直接修复DNA。",ref:"《细胞生物学》第5版 P316",kp:"PARP",tags:["PARP","DNA损伤"]},

      {id:"cell-bio-rare-006",diff:"rare",qt:"single",ct:"defense",cn:"笼形蛋白包被",ec:2,ce:"获得4点护盾",q:"网格蛋白(Clathrin)包被小泡的组装需要哪种GTPase？",opts:["A. ARF和Dynamin","B. Ran","C. Rab","D. Ras"],ans:["A"],exp:"ARF(ADP-ribosylation factor)招募网格蛋白接头蛋白到膜上启动包被组装，Dynamin GTPase负责在颈部切断形成游离囊泡。",ref:"《细胞生物学》第5版 P170",kp:"囊泡运输",tags:["Clathrin","ARF"]},
      {id:"cell-bio-rare-007",diff:"rare",qt:"single",ct:"attack",cn:"次级溶酶体活化",ec:3,ce:"造成7点伤害",q:"关于自噬的mTORC1调控，正确的是？",opts:["A. 营养充足时mTORC1磷酸化ULK1抑制自噬","B. 饥饿时AMPK激活ULK1促进自噬","C. mTORC1定位在溶酶体表面","D. mTORC1通过Rheb激活自噬"],ans:["A","B","C"],exp:"营养充足时mTORC1磷酸化ULK1(Ser757)抑制自噬起始。饥饿时AMPK磷酸化ULK1(Ser317/777)促进自噬。mTORC1经Rag-Ragulator定位在溶酶体表面感受氨基酸。Rheb激活mTORC1但不直接激活自噬。",ref:"《细胞生物学》第5版 P148",kp:"自噬调控",tags:["mTORC1","ULK1"]},
      {id:"cell-bio-rare-008",diff:"rare",qt:"single",ct:"heal",cn:"钙网蛋白修复",ec:2,ce:"恢复5点HP",q:"内质网腔内负责钙离子缓冲的蛋白是？",opts:["A. 钙网蛋白(Calreticulin)和钙联蛋白(Calnexin)","B. BiP和GRP94","C. PDI和ERp57","D. SERCA和IP3R"],ans:["A"],exp:"Calreticulin(可溶)和Calnexin(膜结合)是内质网中主要的Ca²⁺结合蛋白，既是分子伴侣也是钙缓冲蛋白。每个分子可结合约25个Ca²⁺。",ref:"《细胞生物学》第5版 P128",kp:"内质网钙稳态",tags:["钙网蛋白","钙联蛋白"]},

      // 9-36 more rare questions (using simplified format for volume)
      {id:"cell-bio-rare-009",diff:"rare",qt:"single",ct:"attack",cn:"GPCR脱敏",ec:2,ce:"造成6点伤害",q:"GRK( G蛋白偶联受体激酶)的功能是？",opts:["A. 磷酸化活化的GPCR促进β-arrestin结合","B. 激活G蛋白","C. 降解cAMP","D. 合成IP3"],ans:["A"],exp:"GRK磷酸化活化的GPCR，促进β-arrestin结合，导致受体与G蛋白解偶联(同源脱敏)。β-arrestin还可介导内吞和ERK信号。",ref:"《细胞生物学》第5版 P242",kp:"GPCR调控",tags:["GRK","β-arrestin"]},
      {id:"cell-bio-rare-010",diff:"rare",qt:"single",ct:"defense",cn:"内质网出口位点",ec:2,ce:"获得4点护盾",q:"COPII包被小泡的组装起始于内质网的？",opts:["A. ER exit sites (ERES)","B. 内质网全表面","C. 核膜","D. 内质网-线粒体接触点"],ans:["A"],exp:"COPII小泡在内质网特化的出口位点(ERES)组装，Sar1-GTP启动COPII蛋白(Sec23/24,Sec13/31)的招募和聚合。",ref:"《细胞生物学》第5版 P165",kp:"COPII小泡",tags:["COPII","ERES"]},
      {id:"cell-bio-rare-011",diff:"rare",qt:"single",ct:"attack",cn:"Wnt通路激活",ec:3,ce:"造成7点伤害",q:"在无Wnt信号时，β-catenin被什么复合物降解？",opts:["A. 破坏复合体(Axin/APC/GSK3β/CK1)","B. 蛋白酶体直接识别","C. 溶酶体","D. Caspase复合体"],ans:["A"],exp:"无Wnt时，β-catenin被Axin/APC/GSK3β/CK1破坏复合体磷酸化，经β-TrCP泛素化后由蛋白酶体降解。Wnt信号抑制破坏复合体，β-catenin积累入核。",ref:"《细胞生物学》第5版 P254",kp:"Wnt信号",tags:["β-catenin","破坏复合体"]},
      {id:"cell-bio-rare-012",diff:"rare",qt:"single",ct:"heal",cn:"核糖体质量控制",ec:2,ce:"恢复4点HP",q:"核糖体相关质量控制(RQC)识别何种翻译异常？",opts:["A. 停滞的核糖体(stalled ribosome)","B. 过快的翻译","C. 正确的蛋白质折叠","D. tRNA过量"],ans:["A"],exp:"RQC识别并处理停滞的核糖体，由Hel2泛素连接酶标记，Rqc2添加CAT尾巴，Ltn1降解新生链，拯救核糖体亚基。",ref:"《细胞生物学》第5版 P145",kp:"RQC",tags:["RQC","核糖体停滞"]},
      {id:"cell-bio-rare-013",diff:"rare",qt:"single",ct:"attack",cn:"Integrin信号",ec:2,ce:"造成6点伤害",q:"整合素介导的细胞黏附形成的结构称为？",opts:["A. 黏着斑(Focal adhesion)","B. 紧密连接","C. 间隙连接","D. 桥粒"],ans:["A"],exp:"整合素与ECM配体结合后聚集形成黏着斑，招募talin、vinculin、FAK等蛋白，连接肌动蛋白骨架并传递信号。",ref:"《细胞生物学》第5版 P232",kp:"整合素信号",tags:["黏着斑","整合素"]},
      {id:"cell-bio-rare-014",diff:"rare",qt:"single",ct:"defense",cn:"细胞骨架交联",ec:2,ce:"获得4点护盾",q:"中间丝与微管/微丝的主要区别是？",opts:["A. 中间丝无极性，无分子马达沿其运动","B. 中间丝由微管蛋白组成","C. 中间丝仅存在于核内","D. 中间丝是高度动态的"],ans:["A"],exp:"中间丝无极性(组装不需要ATP/GTP)，无已知分子马达沿其运动，比微管和微丝更稳定但韧性更强。",ref:"《细胞生物学》第5版 P214",kp:"中间丝特性",tags:["中间丝","细胞骨架"]},
      {id:"cell-bio-rare-015",diff:"rare",qt:"single",ct:"attack",cn:"Ran GTPase梯度",ec:2,ce:"造成5点伤害",q:"RanGTP在细胞核内高浓度的原因是什么？",opts:["A. RanGEF(RCC1)定位在染色质上","B. RanGAP定位在核内","C. Importin在核内浓度高","D. 核孔复合体不对称"],ans:["A"],exp:"RanGEF(RCC1)结合在染色质上，在核内催化RanGDP→RanGTP，维持核内RanGTP高浓度。RanGAP在胞质，维持胞质RanGDP。此梯度驱动核质运输。",ref:"《细胞生物学》第5版 P270",kp:"Ran梯度",tags:["Ran","RCC1"]},

      // Continue with more rare questions 16-36
      {id:"cell-bio-rare-016",diff:"rare",qt:"truefalse",ct:"heal",cn:"凋亡体组装修复",ec:2,ce:"恢复4点HP",q:"Apaf-1在细胞色素c和dATP存在下组装成凋亡体(apoptosome)，招募并激活Caspase-9。",opts:["A. 正确","B. 错误"],ans:["A"],exp:"细胞色素c释放到胞质后与Apaf-1结合，在dATP/ATP存在下Apaf-1寡聚化形成七元轮盘状凋亡体，通过CARD-CARD相互作用招募Caspase-9并使其激活。",ref:"《细胞生物学》第5版 P346",kp:"凋亡体",tags:["Apaf-1","凋亡体"]},
      {id:"cell-bio-rare-017",diff:"rare",qt:"single",ct:"attack",cn:"mTORC1溶酶体激活",ec:3,ce:"造成7点伤害",q:"mTORC1感知氨基酸丰度的机制依赖于？",opts:["A. Rag GTPase异二聚体和Ragulator复合体","B. TSC复合体","C. AMPK直接激活","D. PI3K通路"],ans:["A"],exp:"氨基酸通过Rag GTPase招募mTORC1至溶酶体表面与Rheb相遇而激活。Ragulator作为Rag的GEF锚定在溶酶体上。",ref:"《细胞生物学》第5版 P152",kp:"mTORC1调控",tags:["mTORC1","Rag GTPase"]},
      {id:"cell-bio-rare-018",diff:"rare",qt:"single",ct:"defense",cn:"SRP介导靶向",ec:2,ce:"获得5点护盾",q:"信号识别颗粒(SRP)识别哪种信号后暂停翻译？",opts:["A. 内质网信号肽(疏水序列)","B. 核定位信号","C. 线粒体导肽","D. 过氧化物酶体靶向信号"],ans:["A"],exp:"SRP识别刚出核糖体的内质网信号肽(含疏水氨基酸)，结合后暂停翻译延长，将核糖体-新生链复合体靶向内质网膜上的SRP受体。",ref:"《细胞生物学》第5版 P126",kp:"SRP",tags:["SRP","信号肽"]},
      {id:"cell-bio-rare-019",diff:"rare",qt:"multiple",ct:"attack",cn:"p53多重打击",ec:3,ce:"造成8点伤害",q:"p53蛋白的哪些功能与其肿瘤抑制角色直接相关？",opts:["A. 激活p21导致G1期阻滞","B. 激活Bax/PUMA促进凋亡","C. 诱导DNA修复基因表达","D. 激活mTOR促进细胞生长"],ans:["A","B","C"],exp:"p53作为转录因子激活p21(细胞周期阻滞)、Bax/PUMA(凋亡)和DNA修复基因(GADD45等)。p53不激活mTOR，实际上p53可抑制mTOR通路。",ref:"《细胞生物学》第5版 P360",kp:"p53功能",tags:["p53","肿瘤抑制"]},
      {id:"cell-bio-rare-020",diff:"rare",qt:"single",ct:"heal",cn:"自噬受体识别",ec:2,ce:"恢复5点HP",q:"p62/SQSTM1在选择性自噬中的关键功能是？",opts:["A. 通过UBA结构域结合泛素化货物，通过LIR结构域结合LC3","B. 直接降解目标蛋白","C. 促进蛋白质合成","D. 激活蛋白酶体"],ans:["A"],exp:"p62/SQSTM1是选择性自噬受体，通过UBA结构域结合泛素化蛋白聚集体，通过LIR(LC3 interacting region)结构域与自噬体膜上的LC3结合，将货物送入自噬体。",ref:"《细胞生物学》第5版 P150",kp:"选择性自噬",tags:["p62","选择性自噬"]},
      {id:"cell-bio-rare-021",diff:"rare",qt:"single",ct:"attack",cn:"p53-MDM2环路",ec:3,ce:"造成7点伤害",q:"MDM2对p53的调控机制是？",opts:["A. MDM2作为E3泛素连接酶促进p53泛素化降解","B. MDM2磷酸化p53","C. MDM2增强p53转录活性","D. MDM2将p53移入细胞核"],ans:["A"],exp:"MDM2是p53最主要的负调控因子，作为E3泛素连接酶直接泛素化p53促使其蛋白酶体降解。p53又转录激活MDM2形成负反馈环路。",ref:"《细胞生物学》第5版 P300",kp:"p53调控",tags:["p53","MDM2","抑癌基因"]},
      {id:"cell-bio-rare-022",diff:"rare",qt:"single",ct:"defense",cn:"DNA损伤检查点",ec:2,ce:"获得5点护盾",q:"ATM激酶被DNA双链断裂激活后的关键底物是？",opts:["A. Chk2和p53","B. Chk1和Cdc25","C. Wee1和MYT1","D. Cyclin B和Cdk1"],ans:["A"],exp:"ATM磷酸化Chk2(Thr68)和p53(Ser15)，Chk2磷酸化Cdc25A/C导致其降解，p53激活p21转录，协同阻断G1/S和G2/M转换。",ref:"《细胞生物学》第5版 P314",kp:"ATM信号",tags:["ATM","Chk2","DNA损伤"]},
      {id:"cell-bio-rare-023",diff:"rare",qt:"single",ct:"heal",cn:"伴侣蛋白修复",ec:2,ce:"恢复5点HP",q:"Hsp70分子伴侣功能的ATP调控模式是？",opts:["A. ATP结合态对底物亲和力低(开放)，ADP结合态亲和力高(闭合)","B. ATP结合态亲和力高","C. 分子伴侣不依赖ATP","D. ATP结合态促进降解"],ans:["A"],exp:"Hsp70：ATP结合态(开放，低亲和力)→J蛋白辅助底物结合和ATP水解→ADP结合态(闭合，高亲和力)→NEF将ADP替换为ATP→底物释放。",ref:"《细胞生物学》第5版 P140",kp:"分子伴侣机制",tags:["Hsp70","分子伴侣","ATPase"]},
      {id:"cell-bio-rare-024",diff:"rare",qt:"single",ct:"attack",cn:"染色质重塑",ec:3,ce:"造成6点伤害",q:"SWI/SNF染色质重塑复合体利用ATP水解能量做什么？",opts:["A. 滑动或移除核小体改变DNA可接近性","B. 修饰组蛋白尾部","C. 甲基化DNA","D. 降解组蛋白"],ans:["A"],exp:"SWI/SNF等ATP依赖染色质重塑因子利用ATP水解能量滑动、移除或替换核小体，调控转录因子对DNA的可接近性。",ref:"《细胞生物学》第5版 P290",kp:"染色质重塑",tags:["SWI/SNF","核小体"]},
      {id:"cell-bio-rare-025",diff:"rare",qt:"multiple",ct:"attack",cn:"缺氧信号通路",ec:3,ce:"造成7点伤害",q:"HIF-1α在常氧条件下被降解的机制包括？",opts:["A. 脯氨酰羟化酶(PHD)羟化HIF-1α","B. VHL泛素连接酶识别羟化HIF-1α","C. 蛋白酶体降解","D. Caspase裂解HIF-1α"],ans:["A","B","C"],exp:"常氧下PHD以氧和α-酮戊二酸为辅因子羟化HIF-1α→VHL识别→VHL作为E3泛素连接酶成分将HIF-1α泛素化→蛋白酶体降解。缺氧时PHD活性下降→HIF-1α稳定→激活靶基因。",ref:"《细胞生物学》第5版 P260",kp:"HIF通路",tags:["HIF-1α","VHL","缺氧"]},
      {id:"cell-bio-rare-026",diff:"rare",qt:"truefalse",ct:"heal",cn:"端粒酶激活",ec:2,ce:"恢复5点HP",q:"端粒酶由TERT(催化亚基)和TERC(RNA模板)组成，利用自身RNA模板合成端粒重复序列TTAGGG。",opts:["A. 正确","B. 错误"],ans:["A"],exp:"端粒酶是一种特殊的逆转录酶。TERC含AAUCCC模板序列，TERT催化亚基以RNA为模板合成TTAGGG重复序列添加到染色体末端。",ref:"《细胞生物学》第5版 P338",kp:"端粒酶",tags:["端粒酶","TERT","TERC"]},
      {id:"cell-bio-rare-027",diff:"rare",qt:"single",ct:"attack",cn:"Hedgehog信号",ec:2,ce:"造成6点伤害",q:"Hedgehog信号通路中，Smo的抑制受体是？",opts:["A. Patched(Ptch)","B. Smoothened(Smo)本身","C. Gli转录因子","D. Sufu"],ans:["A"],exp:"无Hh配体时Patched抑制Smoothened活性，Gli被加工为转录抑制子。Hh配体与Ptch结合解除对Smo的抑制→Smo激活→Gli转录激活子形成→激活靶基因。初级纤毛在此信号转导中至关重要。",ref:"《细胞生物学》第5版 P258",kp:"Hedgehog信号",tags:["Hedgehog","Patched","Smoothened"]},
      {id:"cell-bio-rare-028",diff:"rare",qt:"single",ct:"defense",cn:"细胞极性建立",ec:2,ce:"获得5点护盾",q:"上皮细胞顶-基底侧极性建立的关键蛋白复合体是？",opts:["A. Par复合体(Par3/Par6/aPKC)和Crumbs复合体","B. 仅有紧密连接蛋白","C. 仅有微管组织中心","D. 仅有整合素"],ans:["A"],exp:"上皮极性由三大保守蛋白复合体调控：Par复合体(Par3/Par6/aPKC)、Crumbs复合体(Crb/Pals1/PATJ)和Scribble复合体(Scrib/Dlg/Lgl)。它们相互拮抗建立并维持顶-基底侧极性。",ref:"《细胞生物学》第5版 P228",kp:"细胞极性",tags:["上皮极性","Par复合体"]},
      {id:"cell-bio-rare-029",diff:"rare",qt:"single",ct:"attack",cn:"PI3K-AKT通路",ec:3,ce:"造成7点伤害",q:"PTEN抑癌基因的功能是？",opts:["A. 将PIP3去磷酸化为PIP2，拮抗PI3K信号","B. 直接抑制AKT","C. 降解PI3K","D. 激活mTOR"],ans:["A"],exp:"PTEN作为脂质磷酸酶将PIP3去磷酸化为PIP2，直接拮抗PI3K信号。PTEN是多种肿瘤中最常突变的抑癌基因之一。",ref:"《细胞生物学》第5版 P250",kp:"PTEN",tags:["PTEN","PI3K","PIP3"]},
      {id:"cell-bio-rare-030",diff:"rare",qt:"single",ct:"heal",cn:"PERK信号修复",ec:2,ce:"恢复5点HP",q:"内质网应激中PERK激活后导致的关键结果是？",opts:["A. eIF2α磷酸化→整体翻译减弱但ATF4翻译增强","B. 激活ERK通路","C. 促进内质网降解","D. 激活TOR信号"],ans:["A"],exp:"PERK是UPR三大传感器之一，磷酸化eIF2α的Ser51→整体翻译减弱(降低内质网负担)。但ATF4的uORF使其在eIF2α低活性时反而翻译增强。",ref:"《细胞生物学》第5版 P134",kp:"UPR信号",tags:["PERK","eIF2α","UPR"]},
      {id:"cell-bio-rare-031",diff:"rare",qt:"single",ct:"attack",cn:"TGF-β-Smad",ec:2,ce:"造成6点伤害",q:"TGF-β信号激活的R-Smad是？",opts:["A. Smad2和Smad3","B. Smad1和Smad5","C. Smad4","D. Smad6和Smad7"],ans:["A"],exp:"TGF-β/Activin信号磷酸化R-Smad(Smad2/3)→与Co-Smad(Smad4)形成复合体入核调控转录。BMP信号使用R-Smad(Smad1/5/8)。Smad6/7是抑制性Smad。",ref:"《细胞生物学》第5版 P246",kp:"TGF-β信号",tags:["TGF-β","Smad"]},
      {id:"cell-bio-rare-032",diff:"rare",qt:"single",ct:"defense",cn:"蛋白酶体盖调控",ec:2,ce:"获得4点护盾",q:"19S调节颗粒识别泛素化底物的受体是？",opts:["A. Rpn10和Rpn13","B. Rpt1-6","C. Rpn11","D. α亚基环"],ans:["A"],exp:"26S蛋白酶体的19S调节颗粒中：Rpn10(S5a)和Rpn13通过其泛素结合结构域(UBD)识别多聚泛素链标记的底物；Rpn11是去泛素化酶(DUB)；Rpt1-6是AAA+ ATPase环，负责底物解析叠和转运。",ref:"《细胞生物学》第5版 P150",kp:"泛素-蛋白酶体",tags:["蛋白酶体","19S","泛素"]},
      {id:"cell-bio-rare-033",diff:"rare",qt:"truefalse",ct:"heal",cn:"热休克应答",ec:2,ce:"恢复4点HP",q:"热休克因子HSF1在应激时从Hsp90解离后三聚化并入核，与热休克元件(HSE)结合激活分子伴侣转录。",opts:["A. 正确","B. 错误"],ans:["A"],exp:"HSF1是热休克反应的主调控因子。非应激状态与Hsp90/Hsp70结合滞留胞质(无活性单体)。热/氧化应激→错误折叠蛋白竞争结合Hsp90→HSF1释放→三聚化→入核→结合HSE→激活分子伴侣转录。",ref:"《细胞生物学》第5版 P142",kp:"HSF1",tags:["HSF1","热休克","分子伴侣"]},
      {id:"cell-bio-rare-034",diff:"rare",qt:"single",ct:"attack",cn:"Notch信号",ec:3,ce:"造成7点伤害",q:"Notch受体被激活需要的剪切次数和关键酶是？",opts:["A. 三次剪切：Furin(S1)+ADAM(S2)+γ-分泌酶(S3)","B. 一次剪切：仅Caspase","C. 两次剪切：仅ADAM","D. 无剪切直接激活"],ans:["A"],exp:"Notch受体经历三次蛋白水解剪切：(S1)Furin在高尔基体中完成→异二聚体转运至膜；(S2)ADAM10/17，配体结合触发→切除胞外域；(S3)γ-分泌酶/Presenilin膜内剪切→释放NICD入核激活靶基因。",ref:"《细胞生物学》第5版 P256",kp:"Notch信号",tags:["Notch","γ-分泌酶"]},
      {id:"cell-bio-rare-035",diff:"rare",qt:"single",ct:"debuff",cn:"溶酶体酸化抑制",ec:2,ce:"目标失去2点MP",q:"溶酶体质子泵V-ATPase与F-ATPase的区别是？",opts:["A. V-ATPase水解ATP泵H⁺入溶酶体腔,不可逆;F-ATPase利用H⁺梯度合成ATP","B. 两者相同","C. V-ATPase合成ATP","D. F-ATPase水解ATP酸化"],ans:["A"],exp:"V-ATPase(Vacuolar型)是ATP驱动的质子泵，将H⁺从胞质泵入溶酶体/内体腔使其酸化(pH≈4.5-5.0)，不可逆。F-ATPase(线粒体内膜ATP合酶)利用呼吸链建立的H⁺梯度驱动ATP合成。两者结构同源但功能方向相反。",ref:"《细胞生物学》第5版 P160",kp:"溶酶体酸化",tags:["V-ATPase","溶酶体"]},
      {id:"cell-bio-rare-036",diff:"rare",qt:"multiple",ct:"attack",cn:"细胞衰老特征",ec:3,ce:"造成8点伤害",q:"细胞衰老(cellular senescence)的标志性特征包括？",opts:["A. 持续增殖停滞","B. SASP分泌表型","C. SA-β-Gal活性增高","D. 端粒长度增加"],ans:["A","B","C"],exp:"细胞衰老的三大核心特征：(1)稳定的细胞周期停滞(p16/pRB和p53/p21通路活化)；(2)衰老相关分泌表型(SASP)，分泌IL-6/IL-8/MMPs等；(3)衰老相关β-半乳糖苷酶(SA-β-Gal)活性增高。端粒缩短是衰老的诱因之一，但衰老细胞端粒不增加。",ref:"《细胞生物学》第5版 P340",kp:"细胞衰老",tags:["衰老","SASP","SA-β-Gal"]},
    ].map(function(o){return {id:o.id,subject:"细胞生物学",subjectId:"cell-biology",difficulty:o.diff,questionType:o.qt,cardType:o.ct,cardName:o.cn,energyCost:o.ec,cardEffect:o.ce,question:o.q,options:o.opts,correctAnswers:o.ans,explanation:o.exp,textbookReference:o.ref,knowledgePoint:o.kp,tags:o.tags};}),

    // ========== 史诗题 (18题) ==========
    ...[
      {id:"cell-bio-epic-001",diff:"epic",qt:"single",ct:"attack",cn:"线粒体自噬精准调控",ec:4,ce:"造成10点伤害",q:"PINK1/Parkin介导的线粒体自噬(mitophagy)通路中，PINK1在线粒体外膜积累的信号是？",opts:["A. 线粒体膜电位下降导致PINK1无法被PARL切割","B. PINK1被磷酸化激活","C. Parkin泛素化PINK1","D. 细胞内ATP上升"],ans:["A"],exp:"健康线粒体中PINK1经TOM/TIM转运至内膜被PARL切割后降解。当膜电位下降时PINK1无法进入内膜，在外膜积累并自磷酸化激活，招募并磷酸化Parkin，Parkin泛素化外膜蛋白诱导自噬。",ref:"《细胞生物学》第5版 P122",kp:"线粒体自噬",tags:["PINK1","Parkin","mitophagy"]},
      {id:"cell-bio-epic-002",diff:"epic",qt:"single",ct:"defense",cn:"细胞焦亡屏障",ec:4,ce:"获得8点护盾",q:"Gasdermin D(GSDMD)执行细胞焦亡(pyroptosis)的机制是？",opts:["A. 被Caspase-1/11切割后N端结构域在质膜上形成孔道","B. 激活Bax/Bak","C. 磷酸化MLKL","D. 切割ICAD"],ans:["A"],exp:"炎症性caspase(Caspase-1/4/5/11)切割GSDMD释放其N端成孔结构域(N-GSDMD)，在质膜上寡聚化形成直径约10-15nm的孔道，导致细胞肿胀破裂、释放IL-1β等炎症因子。",ref:"《细胞生物学》第5版 P350",kp:"细胞焦亡",tags:["GSDMD","焦亡"]},
      {id:"cell-bio-epic-003",diff:"epic",qt:"multiple",ct:"attack",cn:"铁死亡诱导",ec:4,ce:"造成12点伤害",q:"铁死亡(ferroptosis)的核心特征包括哪些？",opts:["A. 依赖铁离子和脂质过氧化","B. GPX4活性丧失","C. 线粒体皱缩、嵴减少","D. Caspase激活导致凋亡"],ans:["A","B","C"],exp:"铁死亡是铁依赖的、由脂质过氧化驱动的新型调节性死亡。GPX4失活或System Xc⁻抑制→GSH耗竭→脂质过氧化物积累。形态特征为线粒体皱缩、嵴减少、膜密度增高。不依赖Caspase，不是凋亡。",ref:"《细胞生物学》第5版 P352",kp:"铁死亡",tags:["铁死亡","GPX4","脂质过氧化"]},
      {id:"cell-bio-epic-004",diff:"epic",qt:"single",ct:"heal",cn:"mRNA监视修复",ec:3,ce:"恢复8点HP",q:"无义介导的mRNA衰变(NMD)如何在翻译过程中识别提前终止密码子(PTC)？",opts:["A. 通过外显子连接复合体(EJC)和Upf蛋白识别","B. 通过tRNA识别","C. 通过启动子序列","D. 通过polyA尾部"],ans:["A"],exp:"NMD依赖外显子连接复合体(EJC)。正常终止密码子在最后一个外显子，上游无EJC。若PTC上游存在EJC，Upf蛋白(Upf1/2/3)被激活，招募SMG激酶和RNA酶降解mRNA。",ref:"《细胞生物学》第5版 P280",kp:"NMD",tags:["NMD","EJC","mRNA监控"]},
      {id:"cell-bio-epic-005",diff:"epic",qt:"single",ct:"attack",cn:"相分离异常",ec:3,ce:"造成9点伤害",q:"液-液相分离(LLPS)形成的无膜细胞器中，驱动相分离的主要作用力是？",opts:["A. 固有无序区域(IDR)的多价弱相互作用","B. 共价交联","C. 二硫键","D. 肽键"],ans:["A"],exp:"含有固有无序区域(IDR)的蛋白质通过多价弱相互作用(π-π堆积、阳离子-π、疏水作用等)发生相分离，形成无膜细胞器(如核仁、应激颗粒)。异常相分离与神经退行性疾病相关。",ref:"《细胞生物学》第5版 P35",kp:"相分离",tags:["LLPS","无膜细胞器"]},
      {id:"cell-bio-epic-006",diff:"epic",qt:"multiple",ct:"defense",cn:"复制应激响应",ec:4,ce:"获得8点护盾",q:"ATR激酶在复制应激反应中的关键磷酸化底物包括？",opts:["A. Chk1","B. RPA32","C. BRCA1","D. mTOR"],ans:["A","B","C"],exp:"ATR(ATM-related)识别单链DNA-RPA复合物后激活，磷酸化Chk1(细胞周期检查点)、RPA32(复制叉稳定)和BRCA1(同源重组修复)。mTOR是营养信号通路，不是ATR经典底物。",ref:"《细胞生物学》第5版 P318",kp:"ATR信号",tags:["ATR","复制应激","Chk1"]},
      {id:"cell-bio-epic-007",diff:"epic",qt:"single",ct:"attack",cn:"程序性坏死",ec:4,ce:"造成11点伤害",q:"TNF诱导的程序性坏死(necroptosis)关键执行者是？",opts:["A. RIPK3磷酸化MLKL，MLKL寡聚化破坏质膜","B. Caspase-8切割Bid","C. AIF从线粒体转位入核","D. Cathepsin释放入胞质"],ans:["A"],exp:"当Caspase-8被抑制时，RIPK1/RIPK3形成坏死小体，RIPK3磷酸化MLKL使其寡聚化，MLKL转位至质膜形成孔道导致膜破裂。这是调控性坏死而非意外坏死。",ref:"《细胞生物学》第5版 P348",kp:"程序性坏死",tags:["necroptosis","MLKL","RIPK3"]},
      {id:"cell-bio-epic-008",diff:"epic",qt:"single",ct:"heal",cn:"端粒延长修复",ec:3,ce:"恢复7点HP",q:"ALT(端粒延长替代)途径依赖什么机制维持端粒长度？",opts:["A. 同源重组介导的端粒序列拷贝","B. 端粒酶重新激活","C. 新的端粒从头合成","D. DNA聚合酶延伸"],ans:["A"],exp:"约10-15%的肿瘤通过ALT途径维持端粒，依赖同源重组(BLM、SMC5/6等)和端粒成簇(PML bodies)进行端粒间序列交换延长。无端粒酶活性。",ref:"《细胞生物学》第5版 P314",kp:"ALT途径",tags:["ALT","端粒","同源重组"]},

      // Epic 9-18
      {id:"cell-bio-epic-009",diff:"epic",qt:"multiple",ct:"attack",cn:"内质网应激三重打击",ec:4,ce:"造成10点伤害",q:"UPR三条信号通路的最终效应可包括？",opts:["A. PERK→eIF2α磷酸化→翻译暂停","B. IRE1→XBP1剪接→分子伴侣上调","C. ATF6→高尔基体切割→激活内质网应激元件","D. 均直接导致细胞凋亡"],ans:["A","B","C"],exp:"UPR三条通路首先促进细胞存活(减少翻译负荷、增加分子伴侣)。只有应激无法解决时，PERK→ATF4→CHOP通路才启动凋亡程序。",ref:"《细胞生物学》第5版 P134",kp:"UPR",tags:["UPR","内质网应激"]},
      {id:"cell-bio-epic-010",diff:"epic",qt:"single",ct:"defense",cn:"屏障自噬防御",ec:4,ce:"获得8点护盾",q:"异源自噬(xenophagy)指自噬途径清除什么？",opts:["A. 细胞内病原体(细菌、病毒)","B. 受损线粒体","C. 蛋白质聚集体","D. 过氧化物酶体"],ans:["A"],exp:"异源自噬是选择性自噬的一种，通过泛素化或galectin识别胞内病原体(如沙门氏菌、结核杆菌)，经自噬受体(p62/NDP52/OPTN)将病原体送入自噬溶酶体降解。",ref:"《细胞生物学》第5版 P153",kp:"异源自噬",tags:["异源自噬","病原体"]},
      {id:"cell-bio-epic-011",diff:"epic",qt:"single",ct:"attack",cn:"cGAS-STING感知",ec:3,ce:"造成9点伤害",q:"cGAS-STING通路感知胞质DNA后产生的第二信使是？",opts:["A. 2'3'-cGAMP","B. cAMP","C. cGMP","D. IP3"],ans:["A"],exp:"cGAS结合胞质dsDNA后催化ATP和GTP生成2'3'-cGAMP(非经典的2'-5',3'-5'磷酸二酯键)，cGAMP结合并激活STING，诱导I型干扰素产生。",ref:"《细胞生物学》第5版 P38",kp:"cGAS-STING",tags:["cGAS","STING","天然免疫"]},
      {id:"cell-bio-epic-012",diff:"epic",qt:"single",ct:"heal",cn:"Hippo通路修复",ec:3,ce:"恢复7点HP",q:"Hippo通路的核心激酶级联是？",opts:["A. MST1/2→LATS1/2→YAP/TAZ磷酸化→胞质滞留","B. PI3K→Akt→mTOR","C. Raf→MEK→ERK","D. JAK→STAT"],ans:["A"],exp:"Hippo通路：MST1/2(与SAV1)磷酸化激活LATS1/2(与MOB1)，LATS磷酸化YAP/TAZ使其与14-3-3结合滞留在胞质中，抑制其促增殖转录活性。Hippo通路失活→YAP入核→促进器官增大和肿瘤。",ref:"《细胞生物学》第5版 P264",kp:"Hippo通路",tags:["Hippo","YAP","TAZ"]},
      {id:"cell-bio-epic-013",diff:"epic",qt:"multiple",ct:"attack",cn:"衰老分泌表型",ec:3,ce:"造成9点伤害",q:"细胞衰老的SASP(衰老相关分泌表型)可分泌哪些因子？",opts:["A. IL-6, IL-8等促炎因子","B. MMPs基质金属蛋白酶","C. TGF-β促进旁分泌衰老","D. EGF促进周围细胞增殖"],ans:["A","B","C","D"],exp:"衰老细胞分泌SASP因子（包括IL-6/8、MMPs、TGF-β、生长因子等），可促进炎症、组织重塑和旁分泌衰老，也可能促进邻近癌前细胞增殖。具有复杂的双面效应。",ref:"《细胞生物学》第5版 P375",kp:"SASP",tags:["衰老","SASP"]},
      {id:"cell-bio-epic-014",diff:"epic",qt:"single",ct:"defense",cn:"应激颗粒组装",ec:4,ce:"获得7点护盾",q:"应激颗粒(Stress granule)的核心成核蛋白是？",opts:["A. G3BP1/2","B. TIA-1/TIAR","C. FMRP","D. DDX3X"],ans:["A"],exp:"G3BP1/2是应激颗粒的核心成核蛋白，其过表达促进SG组装，敲除阻断SG形成。G3BP1与停滞翻译起始复合体mRNPs的RNA和蛋白相互作用驱动相分离。",ref:"《细胞生物学》第5版 P145",kp:"应激颗粒",tags:["应激颗粒","G3BP1"]},
      {id:"cell-bio-epic-015",diff:"epic",qt:"single",ct:"attack",cn:"内吞体分选异常",ec:3,ce:"造成8点伤害",q:"ESCRT复合体在MVB(多泡体)形成中的顺序组装正确的是？",opts:["A. ESCRT-0→-I→-II→-III→VPS4解聚","B. ESCRT-III→-II→-I→-0→VPS4","C. ESCRT-I→-III→-0→-II","D. VPS4→ESCRT-0→-I→-II→-III"],ans:["A"],exp:"ESCRT-0识别泛素化膜蛋白并富集，依次招募ESCRT-I、-II、-III，ESCRT-III形成螺旋状聚合物驱动膜内陷和剪切，VPS4 ATPase解聚ESCRT-III循环使用。",ref:"《细胞生物学》第5版 P175",kp:"ESCRT",tags:["ESCRT","MVB"]},
      {id:"cell-bio-epic-016",diff:"epic",qt:"single",ct:"heal",cn:"核孔复合体修复",ec:3,ce:"恢复7点HP",q:"核孔复合体(NPC)中FG-Nups的主要功能是？",opts:["A. 形成选择性通透屏障，通过疏水相互作用介导转运受体通过","B. 维持核膜结构完整性","C. 催化Ran GTP水解","D. 合成核糖体"],ans:["A"],exp:"FG-Nups(含Phe-Gly重复序列)在NPC中央通道形成水凝胶状疏水屏障，转运受体(importin/exportin等)通过与FG重复序列的疏水相互作用穿过此屏障。",ref:"《细胞生物学》第5版 P272",kp:"核孔复合体",tags:["NPC","FG-Nups"]},
      {id:"cell-bio-epic-017",diff:"epic",qt:"multiple",ct:"attack",cn:"蛋白质稳态崩溃",ec:4,ce:"造成12点伤害",q:"蛋白质稳态(proteostasis)网络包括哪些关键组分？",opts:["A. 分子伴侣网络(Hsp70,Hsp90,chaperonin)","B. 泛素-蛋白酶体系统(UPS)","C. 自噬-溶酶体途径(ALP)","D. 未折叠蛋白反应(UPR)"],ans:["A","B","C","D"],exp:"蛋白质稳态由合成、折叠(分子伴侣)、质量控制(泛素-蛋白酶体+自噬)、应激反应(UPR/HSR)等多层网络维持。衰老伴随蛋白质稳态网络整体衰退。",ref:"《细胞生物学》第5版 P342",kp:"蛋白质稳态",tags:["proteostasis","衰老"]},
      {id:"cell-bio-epic-018",diff:"epic",qt:"single",ct:"defense",cn:"屏障自噬防御强化",ec:5,ce:"获得10点护盾",q:"溶酶体功能与mTORC1激活的直接联系依赖于？",opts:["A. Ragulator-Rag复合体在溶酶体膜上的锚定","B. 溶酶体酶活性","C. 自噬体数量","D. 内质网应激水平"],ans:["A"],exp:"氨基酸在溶酶体腔内积累后，经过v-ATPase-Ragulator-Rag GTPase复合体的信号传递，将mTORC1招募至溶酶体表面，使其与Rheb相遇并被激活。这使溶酶体同时作为降解细胞器和信号枢纽。",ref:"《细胞生物学》第5版 P152",kp:"溶酶体信号枢纽",tags:["mTORC1","溶酶体"]},
    ].map(function(o){return {id:o.id,subject:"细胞生物学",subjectId:"cell-biology",difficulty:o.diff,questionType:o.qt,cardType:o.ct,cardName:o.cn,energyCost:o.ec,cardEffect:o.ce,question:o.q,options:o.opts,correctAnswers:o.ans,explanation:o.exp,textbookReference:o.ref,knowledgePoint:o.kp,tags:o.tags};}),

    // ========== 传说题 (6题) ==========
    ...[
      {id:"cell-bio-legend-001",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"legendary",questionType:"single",cardType:"attack",cardName:"线粒体凋亡通路",energyCost:5,cardEffect:"造成15点伤害，无视护盾",question:"Bcl-2家族蛋白调控线粒体外膜通透性(MOMP)的核心机制中，BH3-only蛋白和Bax/Bak的关系是？",options:["A. 激活型BH3-only(Bid/Bim/Puma)直接或间接激活Bax/Bak使其寡聚化形成孔道","B. 抑制型BH3-only抑制Bcl-2","C. Bax/Bak被Caspase直接切割激活","D. BH3-only蛋白封闭线粒体膜孔道"],correctAnswers:["A"],explanation:"MOMP是凋亡不可逆点。激活型BH3-only(Bid/tBid,Bim,Puma)直接激活Bax/Bak构象变化并在线粒体外膜寡聚化形成孔道，或通过中和Bcl-2/BCL-xL间接释放Bax/Bak。Bax/Bak寡聚体孔道释放细胞色素c等凋亡因子。这一机制整合了来自死亡受体(Bid被Caspase-8切割)、DNA损伤(Puma经p53诱导)等多种凋亡信号的输入。",textbookReference:"《医学细胞生物学》第6版 P345-350",knowledgePoint:"线粒体凋亡通路",tags:["Bcl-2","MOMP","凋亡核心机制"]},
      {id:"cell-bio-legend-002",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"legendary",questionType:"single",cardType:"special",cardName:"CRISPR-Cas9基因编辑",energyCost:6,cardEffect:"造成20点伤害，本回合内免疫所有伤害",question:"CRISPR-Cas9系统在真核细胞中实现基因编辑，其核心分子机制关键在于？",options:["A. sgRNA引导Cas9在PAM序列上游产生DNA双链断裂","B. Cas9直接切除整个基因","C. sgRNA翻译后修饰","D. Cas9诱导RNA干扰"],correctAnswers:["A"],explanation:"CRISPR-Cas9编辑系统的核心：设计的sgRNA通过20nt互补序列识别靶DNA位点，Cas9核酸酶识别相邻的PAM(5'-NGG-3')，在PAM上游第3-4碱基处产生DNA双链断裂(DSB)。细胞通过NHEJ(易错，产生indel→基因敲除)或HDR(精确，供体模板→基因敲入)修复DSB。这是2020年诺贝尔化学奖获奖技术。",textbookReference:"《医学细胞生物学》第6版 P420-428",knowledgePoint:"基因编辑技术",tags:["CRISPR","Cas9","基因编辑","Nobel奖"]},
      {id:"cell-bio-legend-003",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"legendary",questionType:"multiple",cardType:"attack",cardName:"细胞死亡交响曲",energyCost:5,cardEffect:"造成18点伤害，目标下回合无法出牌",question:"关于调节性细胞死亡(RCD)亚型的正确对应关系是？",options:["A. 凋亡(apoptosis) — Caspase依赖、细胞皱缩、凋亡小体形成","B. 坏死性凋亡(necroptosis) — RIPK3/MLKL介导、质膜破裂","C. 铁死亡(ferroptosis) — 铁依赖、脂质过氧化、GPX4介导","D. 焦亡(pyroptosis) — GSDMD孔道、炎症因子释放","E. 所有上述对应关系均正确"],correctAnswers:["E"],explanation:"近年研究揭示细胞死亡高度复杂。四种主要调节性死亡类型的区别：凋亡(Caspase-3/7执行、Bcl-2调控、膜完整但PS外翻)；坏死性凋亡(RIPK3→MLKL孔道、膜破裂、DAMPs释放)；铁死亡(铁依赖、GPX4失活→脂质过氧化物堆积、线粒体皱缩)；焦亡(GSDMD孔道→细胞肿胀破裂、IL-1β/IL-18释放→炎症)。2022年后还发现了disulfidptosis(二硫键应激死亡)等新形式。",textbookReference:"《医学细胞生物学》第6版 P340-360",knowledgePoint:"调节性细胞死亡亚型",tags:["凋亡","坏死性凋亡","铁死亡","焦亡","细胞死亡"]},
      {id:"cell-bio-legend-004",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"legendary",questionType:"single",cardType:"special",cardName:"iPS重编程奇迹",energyCost:6,cardEffect:"恢复全部HP并清除所有负面状态",question:"山中伸弥因子(OSKM)将体细胞重编程为iPS细胞时，c-Myc的功能可用什么替代以降低致瘤风险？",options:["A. L-Myc或去除c-Myc用Wnt信号激活剂替代","B. 用抗生素替代","C. 延长培养时间","D. 降低培养温度"],correctAnswers:["A"],explanation:"iPS重编程最初使用OSKM四因子(Oct4, Sox2, Klf4, c-Myc)，但c-Myc是癌基因且其重激活可导致肿瘤(嵌合体小鼠肿瘤率>50%)。后续研究发现：L-Myc同样有效但致瘤性显著降低；p53抑制剂可替代Myc功能；Glis1、Nanog等可部分或完全替代Myc；化学小分子(如VPA, CHIR99021等)可实现化学重编程。2012年山中伸弥因此获诺贝尔生理学或医学奖。",textbookReference:"《医学细胞生物学》第6版 P415-420",knowledgePoint:"iPS细胞重编程",tags:["iPS细胞","山中因子","细胞重编程","Nobel奖"]},
      {id:"cell-bio-legend-005",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"legendary",questionType:"multiple",cardType:"attack",cardName:"肿瘤微环境重塑",energyCost:5,cardEffect:"造成15点伤害，移除目标所有护盾",question:"肿瘤微环境(TME)中癌相关成纤维细胞(CAF)促进肿瘤进展的机制包括？",options:["A. 分泌促血管生成因子(VEGF, FGF)","B. 重塑ECM促进侵袭转移","C. 代谢偶联(反向Warburg效应)","D. 免疫抑制(分泌TGF-β, CXCL12排斥T细胞)","E. 以上全部"],correctAnswers:["E"],explanation:"CAF是TME中最丰富的基质细胞。其促肿瘤机制多元：(1)分泌VEGF/FGF/PDGF驱动血管生成；(2)分泌MMPs和LOX重塑ECM为肿瘤侵袭创造通路；(3)代谢共生：CAF进行有氧糖酵解产生乳酸→肿瘤细胞利用乳酸进行氧化磷酸化(反向Warburg效应)；(4)分泌TGF-β、IL-6、CXCL12等抑制抗肿瘤免疫、排斥T细胞。CAF异质性极高(myCAF/iCAF/apCAF不同亚群功能各异)。靶向FAP+CAF的CAR-T疗法正在临床试验中。",textbookReference:"《医学细胞生物学》第6版 P385-395",knowledgePoint:"肿瘤微环境",tags:["CAF","肿瘤微环境","免疫抑制"]},
      {id:"cell-bio-legend-006",subject:"细胞生物学",subjectId:"cell-biology",difficulty:"legendary",questionType:"single",cardType:"special",cardName:"诺贝尔奖发现",energyCost:7,cardEffect:"造成25点伤害，敌方全体失去2点MP",question:"2023年诺贝尔生理学或医学奖授予Karikó和Weissman的mRNA疫苗技术，其关键突破在于？",options:["A. 假尿苷(Ψ)修饰mRNA降低了先天免疫识别并增强翻译效率","B. 发明了脂质纳米颗粒(LNP)","C. 发现了新冠病毒序列","D. 开发了体外转录技术"],correctAnswers:["A"],explanation:"Karikó和Weissman的核心发现(2005)：将mRNA中的尿苷替换为假尿苷(Ψ)可：(1)避免TLR7/8等先天免疫受体识别；(2)显著增强mRNA翻译效率(10-100倍)；(3)降低RNase L激活。这一突破解决了mRNA治疗的核心障碍——外源mRNA被先天免疫系统攻击。LNP递送技术(Pieter Cullis团队)也是关键贡献但非此次诺贝尔奖内容。mRNA疫苗平台在COVID-19大流行中拯救了数百万生命，开启了mRNA医学新时代。",textbookReference:"《医学细胞生物学》第6版 P430-438",knowledgePoint:"mRNA疫苗技术",tags:["mRNA疫苗","假尿苷","Nobel奖","免疫识别"]}
    ]
  ];
})();
